#!/usr/bin/env bash
# Generated by cs-image-system finalization.
# Phase-ordered deferred commands accumulated during generation.
# NOTE: builders' pre/post finalize hooks are NOT part of this
# script; a --no-dry-run run performs them in-process.
set -euo pipefail
cd "$(dirname "$0")"

# --- phase: image-generation ---
( cd "pckr-ebs-ans/image-generation/block-000" && /usr/local/bin/packer build . )
( cd "pckr-ebs-ans/image-generation/block-001" && /usr/local/bin/packer build . )
( cd "some-other-builder/image-generation/block-000" && packer-1.9.4 build . )
( cd "pckr-ebs-ans/image-generation/block-000" && /usr/local/bin/packer build . )

# --- phase: instance-generation ---
( cd "open-tofu/instance-generation" && /usr/local/bin/tofu plan -input=false )
