# Terraform configuration for Okta users generated by OktaTfUserRoBuilder (okta-tf-users)

terraform {
    required_providers {
        okta = {
            source = "okta/okta"
            version = ">= 6.0"
        }
    }
    
    backend "s3" {
    }
}

provider "okta" {
    org_name = "noaa"
    base_url = "okta.com"
    alias = "okta_tf_users"
}