# Terraform module call for Okta group tcmet generated by OktaTfGroupBuilder (oktagroups)
module "group_tcmet" {
  source                    = "../../../../../tfmodules/okta_opa_module"
  providers                 = { oktapam = oktapam.oktagroups }
  group_id                  = "tcmet"
  members                   = []
  admins                    = ["avery.alpha"]
  delegated_admin_group_ids = []
  account_discovery         = true
  gateway_selector          = "environment=staging"
}