# Terraform module call for Okta group secofs generated by OktaTfGroupBuilder (oktagroups)
module "group_secofs" {
  source                    = "../../../../../tfmodules/okta_opa_module"
  providers                 = { oktapam = oktapam.oktagroups }
  group_id                  = "secofs"
  members                   = ["morganm", "noel", "lennox.lima"]
  admins                    = ["lennox.lima", "avery.alpha", "oakley"]
  delegated_admin_group_ids = []
  account_discovery         = true
  gateway_selector          = "environment=staging"
}