# Terraform module call for Okta group stofs generated by OktaTfGroupBuilder (oktagroups)
module "group_stofs" {
  source                    = "../../../../../tfmodules/okta_opa_module"
  providers                 = { oktapam = oktapam.oktagroups }
  group_id                  = "stofs"
  members                   = ["kendall.kilo", "avery.alpha"]
  admins                    = ["avery.alpha"]
  delegated_admin_group_ids = []
  account_discovery         = true
  gateway_selector          = "environment=staging"
}