# Terraform module call for Okta group coops generated by OktaTfGroupBuilder (oktagroups)
module "group_coops" {
  source                    = "../../../../../tfmodules/okta_opa_module"
  providers                 = { oktapam = oktapam.oktagroups }
  group_id                  = "coops"
  members                   = ["avery.alpha", "casey.charlie"]
  admins                    = ["avery.alpha", "casey.charlie"]
  delegated_admin_group_ids = []
  account_discovery         = true
  gateway_selector          = "environment=staging"
}