# Terraform module call for storage default-bucket generated by TofuS3StorageBuilder (aws-s3)
module "storage_default_bucket" {
  source = "../../../../../tfmodules/aws_storage_s3"
  providers = { aws = aws.aws_s3 }
  bucket_name = "noscsb-csis-test-514190660293-default-bucket"
  public_read = true
  tags = { "env" = "production", "team" = "devops" }
}
output "storage_default_bucket" {
    value = module.storage_default_bucket
    description = "Outputs of storage default-bucket for remote-state consumers"
}