# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""V2 gate 5 (DESIGN §4, phase F1+F2): identity/storage-type plumbing,
activation, admin user and launch parameters.

* base images declare capability on two axes; every declared type's plugin
  bakes its prerequisites, dormant; the mandatory admin user carries public
  keys only; the runtime's session mechanism is the other debug path and
  the no-key-no-session dead end hard-fails (N9);
* an instance image using an undeclared type (either axis) hard-fails the
  run (§3F2); resolution is through pins to the stamped root build (N11);
* an instance image bakes the activation for its OWN owning group;
* launch parameters (mounts, enrollment) are generated by reference,
  recorded in meta-state, and immutable after launch (N26).
"""
from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from v2_support import V2Run, copy_config, tree


@pytest.fixture
def v2(tmp_path, monkeypatch):
    run = V2Run(tmp_path, monkeypatch)
    yield run
    run.restore_cwd()


def _write_yaml(path: Path, data) -> None:
    path.write_text(yaml.safe_dump(data, sort_keys=False))


def _prepared(tmp_path, monkeypatch, mutate):
    root = copy_config(tmp_path)
    mutate(root)
    return V2Run(tmp_path, monkeypatch, config_root=root)


def _set_os_builder(root: Path, name: str, **fields) -> None:
    p = root / "cfg" / "os-builders.yml"
    data = yaml.safe_load(p.read_text())
    for ob in data["os_builders"]:
        if ob["name"] == name:
            ob.update(fields)
    _write_yaml(p, data)


def _set_config(root: Path, **fields) -> None:
    p = root / "cfg" / "_config.yml"
    data = yaml.safe_load(p.read_text())
    data["config"].update(fields)
    _write_yaml(p, data)


def _set_runtime(root: Path, name: str, **fields) -> None:
    p = root / "cfg" / "runtime-builders.yml"
    data = yaml.safe_load(p.read_text())
    for rt in data["runtime_builders"]:
        if rt["name"] == name:
            rt.update(fields)
    _write_yaml(p, data)


def _base_build(v2) -> str:
    return (v2.generated / "base-image" / "pckr-ebs-ans" / "image-generation" / "block-000"
            / "pckr-ebs-ans-image-generation-block-000-build.pkr.hcl").read_text()


def _instance_build(v2) -> str:
    return (v2.generated / "instance-image" / "pckr-ebs-ans" / "image-generation" / "block-000"
            / "pckr-ebs-ans-image-generation-block-000-build.pkr.hcl").read_text()


# ----------------------------------------------------------- base images

def test_base_image_bakes_admin_user_and_declared_prerequisites_dormant(v2):
    assert v2.run(["base-image"], apply=False).ok
    build = _base_build(v2)
    # admin user with the public key, sudo, no password
    assert "useradd -m -s /bin/bash csisadmin" in build
    # stage 49: the key is declared encrypted, so the EMISSION carries its
    # ciphertext; `materialize` puts the key itself in the private copy packer
    # builds from, and nothing in the committed tree holds it
    assert "ENC[age:" in build
    assert "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlaceholderKey" not in build
    assert "NOPASSWD:ALL" in build
    # okta prerequisites: agent installed, DORMANT
    assert "scaleft-server-tools" in build
    assert "systemctl disable --now sftd" in build
    assert "rm -f /var/lib/sftd/enrollment.token" in build
    # storage prerequisites for every declared type on rhel-8/9 ...
    assert "amazon-efs-utils" in build
    assert "awscli" in build
    # ... and nothing for the type my-deb-11 does not declare
    deb = build.split('only   = ["amazon-ebs.my-deb-11"]')
    deb_section = "".join(s.split("provisioner")[0] for s in deb[1:])
    assert "nfs-common" not in deb_section
    # activation NEVER happens on a base image
    assert "sftd.yaml" not in build and "tx.group" not in build


def test_declared_type_without_a_plugin_is_a_hard_failure(tmp_path, monkeypatch):
    run = _prepared(tmp_path, monkeypatch,
                    lambda root: _set_os_builder(root, "basic-rh-10", identity_types=["okta", "ldap"],
                                                 storage_types=["ebs", "lustre"]))
    try:
        summary = run.run(["base-image"], apply=False)
        assert not summary.ok
        errs = "\n".join(summary.validation_errors)
        assert "declares identity type 'ldap' but no identity plugin" in errs
        assert "declares storage type 'lustre' but no storage plugin" in errs
    finally:
        run.restore_cwd()


def test_private_key_material_is_refused(tmp_path, monkeypatch):
    run = _prepared(tmp_path, monkeypatch, lambda root: _set_config(
        root, admin_public_keys=["-----BEGIN " + "OPENSSH PRIVATE KEY-----"]))
    try:
        summary = run.run(["base-image"], apply=False)
        assert not summary.ok
        assert any("PRIVATE key material" in e for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_malformed_key_is_refused(tmp_path, monkeypatch):
    run = _prepared(tmp_path, monkeypatch, lambda root: _set_config(root, admin_public_keys=["not a key"]))
    try:
        summary = run.run(["base-image"], apply=False)
        assert not summary.ok
        assert any("not an OpenSSH public key" in e for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_no_key_and_no_session_is_a_dead_end(tmp_path, monkeypatch):
    def mutate(root):
        _set_config(root, admin_public_keys=[])
        # the fixture now declares SSM on aws-east2 (2026-08-31); the dead
        # end needs NO session mechanism anywhere
        for rt in ("aws-east2-runtime", "aws-east1", "west1"):
            _set_runtime(root, rt, session_mechanism=None, session_instance_profile=None)
    run = _prepared(tmp_path, monkeypatch, mutate)
    try:
        summary = run.run(["base-image"], apply=False)
        assert not summary.ok
        assert any("has NO debug path" in e and "N9 dead end" in e for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_session_mechanism_is_a_debug_path_and_bakes_the_agent(tmp_path, monkeypatch):
    def mutate(root: Path):
        _set_config(root, admin_public_keys=[])
        for rt in ("aws-east2-runtime", "aws-east1", "west1"):
            _set_runtime(root, rt, session_mechanism="ssm", session_instance_profile="csis-session")
    run = _prepared(tmp_path, monkeypatch, mutate)
    try:
        summary = run.run(["base-image", "instance-image"], apply=False)
        assert summary.ok, summary.validation_errors
        build = _base_build(run)
        assert "amazon-ssm-agent" in build
        assert "systemctl enable amazon-ssm-agent" in build
        inst = tree(run.generated / "instance-image" / "open-tofu" / "instance-generation")
        assert 'iam_instance_profile = "csis-session"' in inst["open-tofu-instance-generation-instance-test2.tf"]
        lp = yaml.safe_load((run.meta_state / "launch-params.yaml").read_text())
        assert lp["instances"]["test2"]["session"] == "ssm"
    finally:
        run.restore_cwd()


def test_per_base_image_key_override(tmp_path, monkeypatch):
    run = _prepared(tmp_path, monkeypatch, lambda root: _set_os_builder(
        root, "basic-rh-10", admin_public_keys=["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC override@rhel8"],
        admin_user="ops"))
    try:
        assert run.run(["base-image"], apply=False).ok
        build = _base_build(run)
        assert "useradd -m -s /bin/bash ops" in build
        assert "override@rhel8" in build          # an UNencrypted override is a literal
        # the other base images keep the global list, which is encrypted (stage 49)
        assert "ENC[age:" in build
        assert "csis-admin-placeholder" not in build
    finally:
        run.restore_cwd()


# ------------------------------------------------------ instance images

def test_instance_image_bakes_activation_for_its_own_group(v2):
    assert v2.run(["instance-image"], apply=False).ok
    build = _instance_build(v2)
    # imgfile-basic-dask belongs to coops; imgfile-data-science to stofs
    assert "tx.group: coops" in build
    assert "tx.group: stofs" in build
    dask = build[build.index("identity activation for owning group 'coops'"):].split("provisioner")[1]
    assert "tx.group: coops" in dask and "systemctl enable sftd" in dask
    # activation comes AFTER the image's modifications
    assert build.index('playbook_file = "setup_dask.yml"') < build.index("tx.group: coops")


def test_undeclared_identity_type_breaks_the_cycle(tmp_path, monkeypatch):
    run = _prepared(tmp_path, monkeypatch,
                    lambda root: _set_os_builder(root, "basic-rh-10", identity_types=[]))
    try:
        summary = run.run(["instance-image"], apply=False)
        assert not summary.ok
        assert any("uses an identity type its base 'basic-rh-10' does not declare" in e
                   and "the cycle is broken" in e for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_undeclared_storage_type_breaks_the_cycle(tmp_path, monkeypatch):
    # test2 (image imgfile-basic-dask <- basic-rh-10) mounts the ebs storage mnt_data
    run = _prepared(tmp_path, monkeypatch,
                    lambda root: _set_os_builder(root, "basic-rh-10", storage_types=["efs", "s3"]))
    try:
        summary = run.run(["instance-image"], apply=False)
        assert not summary.ok
        assert any("attaches storage 'mnt_data' of type 'ebs' which base 'basic-rh-10' does not declare" in e
                   for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_capabilities_resolve_through_pins_to_the_stamped_build(tmp_path, monkeypatch):
    """The YAML now declares ebs, but the pinned base build was stamped
    without it: the recorded artifact is the truth (N11)."""
    def mutate(root: Path):
        ms = root / "meta-state"
        ms.mkdir()
        _write_yaml(ms / "lineage.yaml", {"builds": [{
            "build_id": "ami-0base0001", "series": "basic-rh-10", "name": "basic-rh-10-x",
            "capabilities": {"identity_types": ["okta"], "storage_types": ["efs", "s3"]}}]})
        _write_yaml(ms / "pins.yaml", {"images": {"imgfile-basic-dask": "ami-0base0001"}, "instances": {}})
    run = _prepared(tmp_path, monkeypatch, mutate)
    try:
        summary = run.run(["instance-image"], apply=False)
        assert not summary.ok
        assert any("via pin:ami-0base0001" in e and "type 'ebs'" in e for e in summary.validation_errors)
    finally:
        run.restore_cwd()


def test_chain_inherits_the_root_stamp(tmp_path, monkeypatch):
    """imgfile-basic-cloudflow chains off imgfile-basic-dask (which chains off
    basic-rh-10); its capabilities are the root's (N24)."""
    run = V2Run(tmp_path, monkeypatch)
    try:
        from cs_image_system.base.capabilities import effective_capabilities, image_chain
        img = run.ctx.images_map["imgfile-basic-cloudflow"]
        chain, root = image_chain(run.ctx, img)
        assert chain == ["imgfile-basic-cloudflow", "imgfile-basic-dask"] and root == "basic-rh-10"
        caps = effective_capabilities(run.ctx, img)
        assert caps is not None
        assert caps.identity_types == ["okta"] and caps.storage_types == ["ebs", "efs", "gcs", "pd", "s3"]
        assert caps.source == "declaration"
    finally:
        run.restore_cwd()


# ----------------------------------------------------- launch parameters

def test_launch_parameters_are_generated_by_reference_and_recorded(v2):
    assert v2.run(["instance-image"], apply=False).ok
    inst = tree(v2.generated / "instance-image" / "open-tofu" / "instance-generation")
    module = inst["open-tofu-instance-generation-instance-test2.tf"]
    assert 'templatefile("${path.module}/user-data-test2.sh.tftpl"' in module
    assert 'data.terraform_remote_state.oktagroups.outputs.group_gids["coops"]' in module
    assert 'data.terraform_remote_state.aws_ebs.outputs.storage_mnt_data.volume_id' in module
    assert '"device_name" = "/dev/xvdf"' in module
    assert "var.sft_enrollment_token" in module
    tpl = inst["user-data-test2.sh.tftpl"]
    # device resolution: legacy name first, Nitro by-id fallback from the
    # volume id (found live: /dev/xvdf never appears on t3/Nitro)
    assert "DEV='/dev/xvdf'" in tpl and "/mnt/data" in tpl
    assert 'ebs["mnt_data"].volume_id' in tpl
    assert "nvme-Amazon_Elastic_Block_Store_" in tpl
    assert 'mkfs -t xfs "$DEV"' in tpl
    assert "chgrp \"$GID\" '/mnt/data/coops'" in tpl and "chmod 2770 '/mnt/data/coops'" in tpl
    assert "/var/lib/sftd/enrollment.token" in tpl
    root = inst["open-tofu-instance-generation.tf"]
    assert 'variable "sft_enrollment_token"' in root and "sensitive = true" in root
    assert 'data "terraform_remote_state" "oktagroups"' in root
    lp = yaml.safe_load((v2.meta_state / "launch-params.yaml").read_text())
    rec = lp["instances"]["test2"]
    assert rec["group"] == "coops" and rec["identity_type"] == "okta"
    assert rec["mounts"][0] == {"storage": "mnt_data", "type": "ebs", "builder": "aws-ebs",
                                "mount_point": "/mnt/data", "group": "coops", "share_mode": "2770",
                                "public_read": False, "device": "/dev/xvdf"}
    assert rec["enrollment"] == {"enrollment": "sftd-token", "server_label": "sftd.tx.group=coops"}
    assert rec["launched"] is False
    assert "token" not in yaml.safe_dump(rec).replace("sftd-token", "").replace("enrollment.token", "")


def test_launch_parameters_are_immutable_after_launch(tmp_path, monkeypatch):
    run = V2Run(tmp_path, monkeypatch)
    try:
        assert run.run(["instance-image"], apply=False).ok
        # simulate the apply that launched test2
        ms = run.ctx.meta_state
        rec = dict(ms.launch_params()["test2"])
        rec["launched"] = True
        rec["launched_run"] = "2026_08_01t00_00_00"
        ms.record_launch_params("test2", rec)
        # same parameters: fine
        assert run.run(["instance-image"], apply=False).ok
        # change the mount point -> hard failure
        p = run.config_root / "instances" / "instances.yaml"
        data = yaml.safe_load(p.read_text())
        data["instances"][1]["storages"][0]["mount_point"] = "/data"
        _write_yaml(p, data)
        run.restore_cwd()
        run2 = V2Run(tmp_path, monkeypatch, config_root=run.config_root)
        summary = run2.run(["instance-image"], apply=False)
        assert not summary.ok
        assert any("launch parameters are immutable after launch" in e and "'test2'" in e
                   for e in summary.validation_errors)
        # ... unless the instance is being replaced by an explicit upgrade
        run2.ctx.meta_state.move_pin("instance", "test2", "ami-0new", run2.ctx.run_id)
        assert run2.run(["instance-image"], apply=False).ok
        cmds = (run2.generated / "instance-image" / "run-instance-image.sh").read_text()
        assert "-replace=module.instance_test2.aws_instance.this" in cmds
        assert "--allow-destroy module.instance_test2.aws_instance.this" in cmds
        run2.restore_cwd()
    finally:
        run.restore_cwd()


def test_decommissioned_instance_is_whitelisted_and_forgotten(tmp_path, monkeypatch):
    def mutate(root: Path):
        ms = root / "meta-state"
        ms.mkdir()
        _write_yaml(ms / "launch-params.yaml", {"instances": {"old_node": {"launched": True, "image": "x"}}})
        _write_yaml(ms / "pins.yaml", {"instances": {"old_node": "ami-0old"}, "images": {}})
    run = _prepared(tmp_path, monkeypatch, mutate)
    try:
        # a DRY run whitelists the destroy but must NOT forget the record yet
        # (finding 53: forgetting at generation let a dry run erase the record
        # before any destroy ran, leaving nothing to whitelist afterwards)
        assert run.run(["instance-image"], apply=False).ok
        cmds = (run.generated / "instance-image" / "run-instance-image.sh").read_text()
        assert "--allow-destroy module.instance_old_node" in cmds
        lp = yaml.safe_load((run.meta_state / "launch-params.yaml").read_text())
        assert "old_node" in lp["instances"]
        pins = yaml.safe_load((run.meta_state / "pins.yaml").read_text())
        assert "old_node" in pins["instances"]
        assert not any(u.get("op") == "decommission" for u in pins.get("upgrades", []))
        # the REAL apply (flag on) destroys through the gate, then forgets
        _set_config(run.config_root, apply_instances=True)
        run.restore_cwd()
        run = V2Run(tmp_path, monkeypatch, config_root=run.config_root)   # reload the flag
        assert run.run(["instance-image"], apply=False).ok
        # simulate the apply that destroyed old_node (the harness's stubbed
        # apply step fires no hooks): the after-apply forget, flag on
        from cs_image_system.base.launch_params import forget_decommissioned
        from cs_image_system.base.lifecycles import Lifecycle
        forget_decommissioned(run.ctx, Lifecycle.INSTANCE_IMAGE)
        lp = yaml.safe_load((run.meta_state / "launch-params.yaml").read_text())
        assert "old_node" not in lp["instances"]
        pins = yaml.safe_load((run.meta_state / "pins.yaml").read_text())
        assert "old_node" not in pins["instances"]
        assert pins["upgrades"][-1]["op"] == "decommission"
    finally:
        run.restore_cwd()


def test_instance_module_keeps_original_image(v2):
    """Belt and braces (§3F5): the module ignores AMI drift."""
    module = (Path(__file__).resolve().parents[1] / "tfmodules" / "aws_instance" / "main.tf").read_text()
    assert "ignore_changes = [ami, user_data]" in module
    assert 'resource "aws_volume_attachment"' in module
