# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""Stage 70, iteration one: the bootstrap -- the question model, the quiet
interview, the answers file, the GitHub section and its module, the root
regenerated by every run and judged by config-drift, the secrets script,
the starters carrying the module, the recipe and the ignore exception.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

from tests.v2_support import V2Run, copy_config


def _assigned(text: str, key: str, value: str) -> bool:
    """``key = value`` on a line of HCL, however aligned."""
    return re.search(rf"^\s*{re.escape(key)}\s*=\s*{re.escape(value)}\s*$", text, flags=re.M) is not None

from cs_image_system.base import bootstrap as bs
from cs_image_system.base.bootstrap.facts import Facts, parse_remote
from cs_image_system.base.bootstrap.questions import Question, Refused, Rendered, Section

REPO = Path(__file__).resolve().parents[1]
EXAMPLES = REPO / "docs" / "examples"
TREES = ("standard-aws", "standard-gce", "complete")

GITHUB_ANSWERS = {"github": {
    "wanted": True, "repository": "acme/widgets", "default_branch": "develop", "production_branch": "main",
    "protect_production": True, "perform_runtime": "aws-east2-runtime", "guard_runtime": "gcloud-east1",
    "aws_region": "us-east-2", "secrets_dir": "_uncommitted/secrets"}}


def _git(root: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(root), *args], check=True, capture_output=True, text=True).stdout


def _starter_copy(tmp_path: Path, name: str = "standard-aws", remote: str | None = "git@github.com:acme/widgets.git") -> Path:
    root = tmp_path / "tree"
    shutil.copytree(EXAMPLES / name, root)
    _git(root, "init", "-q", "-b", "develop")
    _git(root, "config", "user.email", "t@example.invalid")
    _git(root, "config", "user.name", "t")
    if remote:
        _git(root, "remote", "add", "origin", remote)
    return root


# ------------------------------------------------------------ the question model

def test_questions_defaults_conditions_and_coercion():
    facts = Facts(config_root=Path("."), owner="acme", repo="widgets")
    literal = Question("a", "A?", default="x")
    derived = Question("b", "B?", default=lambda f, a: f.repository)
    gated = Question("c", "C?", kind="bool", default=True, when=lambda a: a.get("a") == "x")
    assert literal.default_for(facts, {}) == "x" and derived.default_for(facts, {}) == "acme/widgets"
    assert gated.applies({"a": "x"}) and not gated.applies({"a": "y"})
    assert gated.coerce("no") is False and gated.coerce("Y") is True
    with pytest.raises(Refused):
        gated.coerce("maybe")
    choice = Question("d", "D?", kind="choice", choices=("s3", "local"), default="s3")
    assert choice.coerce("local") == "local"
    with pytest.raises(Refused):
        choice.coerce("gcs")
    with pytest.raises(ValueError):
        Question("e", "E?", kind="choice")                         # a choice needs choices
    assert parse_remote("git@github.com:acme/widgets.git") == ("acme", "widgets")
    assert parse_remote("https://github.com/acme/widgets") == ("acme", "widgets")
    assert parse_remote("ssh://elsewhere/x.git") is None


def _section(questions, name="probe"):
    return Section(name=name, title=name, questions=tuple(questions), render=lambda a: Rendered())


def test_the_quiet_interview_takes_defaults_and_refuses_what_it_cannot_derive():
    facts = Facts(config_root=Path("."))
    s = _section([Question("repo", "Repository?", default=lambda f, a: f.repository, help="from git remote"),
                  Question("branch", "Branch?", default="main")])
    with pytest.raises(Refused, match=r"probe\.repo: Repository\? -- no default can be derived \(from git remote\)"):
        bs.run_interview([s], facts, quiet=True)
    facts.owner, facts.repo = "acme", "widgets"
    out = bs.run_interview([s], facts, quiet=True)
    assert out == {"probe": {"wanted": True, "repo": "acme/widgets", "branch": "main"}}
    # earlier answers win over the question's default, and --section keeps the others untouched
    prior = {"probe": {"wanted": True, "repo": "acme/other", "branch": "trunk"}, "aws": {"wanted": True, "x": 1}}
    out = bs.run_interview([s], facts, quiet=True, prior=prior)
    assert out["probe"] == {"wanted": True, "repo": "acme/other", "branch": "trunk"} and out["aws"] == {"wanted": True, "x": 1}
    out = bs.run_interview([s], facts, quiet=True, prior={"probe": {"wanted": False}})
    assert out["probe"] == {"wanted": False}                        # a section not wanted asks nothing
    # the interactive path: a scripted asker, the gate first, defaults shown
    asked: list[tuple[str, object]] = []
    def ask(prompt, default, kind, choices):
        asked.append((prompt, default))
        return {"Repository?": "acme/typed"}.get(prompt, default)
    out = bs.run_interview([s], facts, ask=ask)
    assert out["probe"]["repo"] == "acme/typed" and out["probe"]["branch"] == "main"
    assert asked[0][0] == "Do you want the probe section?" and asked[1] == ("Repository?", "acme/widgets")


def test_the_answers_file_round_trips_and_is_versioned(tmp_path: Path):
    p = tmp_path / "bootstrap.yaml"
    bs.write_answers(p, {"github": {"wanted": True, "repository": "acme/widgets"}})
    text = p.read_text()
    assert text.startswith("# cs-image-system bootstrap") and "version: 1" in text
    assert bs.read_answers(p) == {"github": {"wanted": True, "repository": "acme/widgets"}}
    assert bs.read_answers(tmp_path / "absent.yaml") == {}
    p.write_text("version: 7\nsections: {}\n")
    with pytest.raises(ValueError, match="version 7"):
        bs.read_answers(p)


# ------------------------------------------------------ the GitHub section's root

def test_a_quiet_interview_over_a_starter_writes_the_answers_and_the_root(tmp_path: Path):
    root = _starter_copy(tmp_path)
    facts = bs.gather(root, gh=False)
    assert facts.repository == "acme/widgets" and facts.module_source_base == "tfmodules"
    assert facts.runtimes and facts.runtimes[0]["name"]             # the starter's raw cfg was read without loading
    answers = bs.run_interview(bs.discover(), facts, quiet=True, only=["github"])
    github = answers["github"]
    assert github["wanted"] and github["repository"] == "acme/widgets" and github["production_branch"] == "main"
    assert github["perform_runtime"] == facts.runtimes[0]["name"] or github["perform_runtime"]
    bs.write_answers(root / bs.ANSWERS_FILE, answers)
    written = bs.regenerate(root)
    out = bs.output_dir(root)
    assert written and sorted(p.name for p in written) == sorted(
        [".gitignore", "README.md", "bootstrap.auto.tfvars", "main.tf", "outputs.tf", "providers.tf", "set-secrets.sh", "variables.tf"])
    main = (out / "main.tf").read_text()
    assert _assigned(main, "source", '"../../tfmodules/bootstrap_github"')   # re-rooted from generated/bootstrap
    assert _assigned(main, "repository", "var.github_repository")
    tfvars = (out / "bootstrap.auto.tfvars").read_text()
    assert _assigned(tfvars, "github_repository", '"acme/widgets"') and _assigned(tfvars, "github_protect_production", "true")
    assert 'backend "local" {}' in (out / "providers.tf").read_text()
    assert os.access(out / "set-secrets.sh", os.X_OK)
    assert "!bootstrap.auto.tfvars" in (out / ".gitignore").read_text()
    # the tfvars is pinned: the answers alone decide the bytes
    pinned = bs.regenerate(root)
    assert pinned and (out / "bootstrap.auto.tfvars").read_text() == tfvars


def test_the_secrets_script_names_every_guide_secret_and_no_value(tmp_path: Path):
    root = _starter_copy(tmp_path)
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    bs.regenerate(root)
    script = (bs.output_dir(root) / "set-secrets.sh").read_text()
    guide = (EXAMPLES / "complete" / "CI_SETUP.md").read_text()
    body = guide[guide.index("### 3.7 The secrets"):]
    body = body[:body.index("\n### ", 1)]
    names = set(re.findall(r"^\| `([A-Z0-9_]+)` \|", body, flags=re.M))
    assert names and all(f"from_file {n}" in script or f"from_output {n} " in script for n in names), names
    assert 'DIR="${SECRETS_DIR:-_uncommitted/secrets}"' in script and 'REPO="${REPO:-acme/widgets}"' in script
    assert "AKIA" not in script and "BEGIN" not in script             # no value, ever


@pytest.mark.skipif(shutil.which("tofu") is None, reason="tofu not installed")
def test_the_generated_root_validates_with_tofu(tmp_path: Path):
    from tests.test_v2_gcp_increment3 import private_plugin_cache
    root = _starter_copy(tmp_path)
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    bs.regenerate(root)
    out = bs.output_dir(root)
    env = {**os.environ, "TF_PLUGIN_CACHE_DIR": str(private_plugin_cache(tmp_path, [out]))}
    for args in (["init", "-backend=false", "-input=false", "-no-color"], ["validate", "-no-color"]):
        res = subprocess.run(["tofu", *args], cwd=out, capture_output=True, text=True, timeout=600, env=env)
        assert res.returncode == 0, f"tofu {args[0]}\n{res.stdout}\n{res.stderr}"


# ----------------------------------------------------- the root inside every run

@pytest.fixture
def world(tmp_path: Path, monkeypatch):
    root = copy_config(tmp_path)
    runs: list[V2Run] = []

    def make(**kw) -> V2Run:
        run = V2Run(tmp_path, monkeypatch, config_root=root, **kw)
        runs.append(run)
        return run
    try:
        yield root, make
    finally:
        for r in runs:
            r.restore_cwd()


def _bytes(out: Path) -> dict[str, bytes]:
    return {p.relative_to(out).as_posix(): p.read_bytes() for p in sorted(out.rglob("*")) if p.is_file()}


def test_every_run_regenerates_the_root_from_the_answers_and_prunes_without_them(world):
    root, make = world
    run = make()
    assert run.run(["identity"], apply=False).ok
    assert not bs.output_dir(root).exists()                         # the frozen fixture carries no answers: nothing
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    run = make()
    summary = run.run(["identity"], apply=False)
    assert summary.ok, summary.validation_errors or summary.error
    out = bs.output_dir(root)
    first = _bytes(out)
    assert "main.tf" in first and "bootstrap.auto.tfvars" in first
    assert b"../../../tfmodules/bootstrap_github" in first["main.tf"]  # the fixture's ../tfmodules, re-rooted
    run = make()
    assert run.run(["identity"], apply=False).ok
    assert _bytes(out) == first                                       # deterministic: the same bytes
    (root / bs.ANSWERS_FILE).unlink()
    run = make()
    assert run.run(["identity"], apply=False).ok
    assert not out.exists()                                           # pruned with the answers


def test_a_commit_run_stages_the_root_and_its_tfvars(world):
    root, make = world
    _git(root, "init", "-q")
    _git(root, "config", "user.email", "t@example.invalid")
    _git(root, "config", "user.name", "t")
    (root / ".gitignore").write_text("*.tfvars\n!generated/bootstrap/bootstrap.auto.tfvars\n*.tfstate\n")
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    run = make()
    summary = run.run(["identity"], apply=False, commit=True)
    assert summary.ok and summary.meta_state_commit, summary.error
    staged = _git(root, "ls-tree", "-r", "--name-only", "HEAD", "generated/bootstrap").split()
    assert "generated/bootstrap/main.tf" in staged and "generated/bootstrap/bootstrap.auto.tfvars" in staged
    assert "generated/bootstrap/.gitignore" in staged


def test_config_drift_judges_the_bootstrap_root(tmp_path: Path):
    from cs_image_system.base.commands.emission import config_drift
    root = tmp_path / "cfgtree"
    (root / "cfg").mkdir(parents=True)
    (root / "cfg" / "_config.yml").write_text("config:\n  module_source_base: tfmodules\n")
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    bs.regenerate(root)
    _git(root, "init", "-q")
    _git(root, "config", "user.email", "t@example.invalid")
    _git(root, "config", "user.name", "t")
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "the bootstrap root")

    def dry(copy: Path) -> None:           # what a headless dry run does to the copy, for this tree
        bs.regenerate(copy)
    code, lines = config_drift(root, dry_run=dry)
    assert code == 0, lines
    main = root / "generated" / "bootstrap" / "main.tf"
    main.write_text(main.read_text() + "\n# edited by hand\n")
    _git(root, "commit", "-q", "-am", "a hand edit")
    code, lines = config_drift(root, dry_run=dry)
    assert code == 1 and "BEHIND the configuration (1 files)" in lines[0] and any("edited by hand" in ln for ln in lines)
    # and an answer that changed moves the root: the committed one is behind until a run regenerates it
    bs.regenerate(root)                     # back to the honest root
    _git(root, "commit", "-q", "-am", "regenerated")
    answers = bs.read_answers(root / bs.ANSWERS_FILE)
    answers["github"]["production_branch"] = "release"
    bs.write_answers(root / bs.ANSWERS_FILE, answers)
    _git(root, "commit", "-q", "-am", "an answer changed")
    code, lines = config_drift(root, dry_run=dry)
    assert code == 1 and any('"release"' in ln for ln in lines)


# ------------------------------------------------------------- the release's parts

def test_the_starters_carry_the_module_the_recipe_and_the_ignore_exception():
    for name in TREES:
        tree = EXAMPLES / name
        assert (tree / "tfmodules" / "bootstrap_github" / "main.tf").read_bytes() == (REPO / "tfmodules" / "bootstrap_github" / "main.tf").read_bytes()
        assert re.search(r"^bootstrap \*ARGS:\n\t@\{\{cli\}\} bootstrap \{\{ARGS\}\}", (tree / "Justfile").read_text(), flags=re.M), name
        ignore = (tree / ".gitignore").read_text().splitlines()
        assert "*.tfvars" in ignore and "!generated/bootstrap/bootstrap.auto.tfvars" in ignore, name
        assert ignore.index("*.tfvars") < ignore.index("!generated/bootstrap/bootstrap.auto.tfvars")


def test_public_safe_passes_over_a_generated_root(tmp_path: Path):
    from cs_image_system.base.public_safe import scan_tree
    root = _starter_copy(tmp_path)
    bs.write_answers(root / bs.ANSWERS_FILE, GITHUB_ANSWERS)
    bs.regenerate(root)
    out = bs.output_dir(root)
    files = [str(p.relative_to(root)) for p in out.rglob("*") if p.is_file()] + [bs.ANSWERS_FILE]
    assert scan_tree(root, files=files) == []


def test_the_command_runs_without_loading_and_refuses_by_name_under_quiet(tmp_path: Path):
    from typer.testing import CliRunner
    from cs_image_system.system.cli import app
    root = _starter_copy(tmp_path, remote=None)                      # no remote: the repository has no default
    quiet = ["--root-dir", str(root), "bootstrap", "--quiet", "--section", "github"]
    res = CliRunner().invoke(app, quiet)
    assert res.exit_code == 2 and "refused: github.repository" in res.output, res.output
    assert not (root / bs.ANSWERS_FILE).exists()
    _git(root, "remote", "add", "origin", "https://github.com/acme/widgets.git")
    res = CliRunner().invoke(app, quiet)
    assert res.exit_code == 0, res.output
    assert "sections wanted: github" in res.output and "wrote generated/bootstrap/main.tf" in res.output
    assert "by hand, still:" in res.output and "tofu init && tofu plan && tofu apply" in res.output
    answers = yaml.safe_load((root / bs.ANSWERS_FILE).read_text())
    assert answers["sections"]["github"]["repository"] == "acme/widgets"
    # a second quiet interview keeps the answers (they are the defaults now) and the bytes
    before = _bytes(bs.output_dir(root))
    res = CliRunner().invoke(app, quiet)
    assert res.exit_code == 0 and _bytes(bs.output_dir(root)) == before
