# Build configuration for Packer EBS Ansible Builder generated by PackerEbsImageBuilder (some-other-builder)
build {
  name = "some-other-builder-block-000"
  sources = [
"source.amazon-ebs.imgfile-basic-cloudflow-notdocker"
]
  # identity activation for owning group 'secofs' (okta)
  provisioner "shell" {
    only   = ["amazon-ebs.imgfile-basic-cloudflow-notdocker"]
    inline = [
      "# identity activation for group 'secofs' (okta) on image imgfile-basic-cloudflow-notdocker",
      "sudo mkdir -p /etc/sft",
      "printf 'Labels:\\n  tx.group: secofs\\n' | sudo tee /etc/sft/sftd.yaml",
      "sudo systemctl enable sftd",
    ]
  }
  # in-bake verification for instance image imgfile-basic-cloudflow-notdocker: 2 assertion(s)
  provisioner "shell" {
    only   = ["amazon-ebs.imgfile-basic-cloudflow-notdocker"]
    inline = [
      "set -e",
      "# verify: activated for group 'secofs'",
      "grep -q 'tx.group: secofs' /etc/sft/sftd.yaml",
      "systemctl is-enabled sftd >/dev/null 2>&1",
    ]
  }
  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}