# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

import copy
from graphlib import TopologicalSorter
import json
import logging
from pathlib import Path
from typing import Any, cast
import hcl2
from hcl2 import Builder

from cs_image_system.base.basic.asset import Asset, AssetSet
from cs_image_system.base.constants import SELF
from cs_image_system.base.global_context import GlobalTypeContext
from cs_image_system.base.lifecycle import ExecutionLifecyclePhase
from cs_image_system.base.models.base_image import BaseImage
from cs_image_system.base.models.executable import ExecutableModel
from cs_image_system.base.models.executable_adds import CFExecutables
from cs_image_system.base.models.image import Image
from cs_image_system.base.models.moditem_type import ModItemModel
from cs_image_system.base.models.provider_specific_image import PSISourceKind
from cs_image_system.hashicorp_utils.hashicorp import FO # noqa: F401
from .packer_models import PackerEbsImageBuilderModel  # PACKER_EBS is defined locally below
from .packer_builder import PackerImageBuilder

log = logging.getLogger(__name__)


PACKER_EBS: str = "packer-ebs"
PACKER_PLUGIN_TYPE: str = "PackerPlugin"
MANIFEST_FILENAME: str = "manifest.json"


def parse_packer_manifest(manifest_path: Path, rtb: Any = None) -> dict[str, str]:
    """Parse a packer manifest into {image name: build id}.

    Only builds from the manifest's last run are considered. Build names are
    the packer source labels, which this builder sets to the image name; the
    runtime plugin turns ``artifact_id`` into its build id (amazon-ebs:
    '<region>:<ami-id>' -> ami id; googlecompute: the image name).
    """
    if not manifest_path.is_file():
        log.warning(f"No packer manifest at {manifest_path}; built image ids unavailable")
        return {}
    try:
        data = json.loads(manifest_path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        log.error(f"Could not parse packer manifest {manifest_path}: {e}")
        return {}
    last_run = data.get("last_run_uuid")
    results: dict[str, str] = {}
    for build in data.get("builds", []):
        if last_run and build.get("packer_run_uuid") != last_run:
            continue
        name = build.get("name")
        artifact = build.get("artifact_id") or ""
        identifier = (rtb.build_id_from_artifact(artifact) if rtb is not None
                      else artifact.split(":")[-1]) if artifact else None
        if name and identifier:
            results[name] = identifier
    return results

class PackerEbsImageBuilder(PackerImageBuilder[PackerEbsImageBuilderModel]):
    """Packer image builder implementation for Amazon EBS with Ansible."""

    @classmethod
    def csis_name(cls) -> str:
        return PACKER_EBS


    def generate_items_before(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet: # list[tuple[Path, str]]:
        """Generate a list of items to create before a specific execution lifecycle
        event."""
        super_items = super().generate_items_before(phase)
        items: AssetSet = AssetSet()
        if phase == ExecutionLifecyclePhase.IMAGE_GENERATION:
            blocks, blocks_map = self.get_blocks()
            if blocks:
                log.debug(f"Blocks for image generation (before): {blocks}")
                # super().generate_items_before registered this builder's
                # plugins/variables into the PackerCollector; each block dir is
                # its own packer root, so emit the setup + vars per block.
                from cs_image_system.hashicorp_utils.collector import PackerCollector
                col = PackerCollector()
                ws = self.get_discriminator()
                for block in blocks:
                    vpath = self.get_block_path_for_phase(phase,block = block, suffix="-vars.pkr.hcl")
                    items.add(vpath, "# Packer variables configuration")
                    items.add(vpath, f"#  Generated by {ws} ({self.model.__class__.__name__})")
                    items.add_list(vpath, col.generate_variable_blocks(ws))
                    ppath = self.get_block_path_for_phase(phase, block=block, suffix="-plugins.pkr.hcl")
                    items.add(ppath, f"# Packer required plugins generated by {self.__class__.__name__} ({self.name})")
                    items.add_list(ppath, col.generate_packer_block(ws))

                    setup_path = self.get_block_path_for_phase(phase, block=block, suffix="-ebs-ansible-setup.pkr.hcl")
                    items.add(
                            setup_path,
                            f"# Additional setup for Packer EBS Ansible Builder generated by "
                            f"{self.__class__.__name__} ({self.name})",
                    )

                    ctent: dict[str, Any] = {
                        "snapshot": 'var.release ? "" : "-SNAPSHOT"',
                        "image_version": '"${var.base_image_version}${local.snapshot}"',
                    }

                    doc = Builder()
                    lblock = doc.block("locals", **ctent)
                    localslines = hcl2.dumps(doc.build(), formatter_options=FO).splitlines()
                    items.add_list(setup_path, localslines)
                    items.add(setup_path, "")

                    # items.append(Asset((setup_path, "")))
                    # Add more specific configuration as needed


            # Add additional setup for EBS with Ansible

        return items
    def generate_items_during(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """Generate a list of items to create during a specific execution
        lifecycle event."""

        ctx = GlobalTypeContext()
        items: AssetSet = AssetSet()

        if phase == ExecutionLifecyclePhase.IMAGE_GENERATION:
            blocks,block_map = self.get_blocks()
            if blocks:
                log.debug(f"Blocks determined for image generation: {blocks}")
                for block in blocks:
                    # Assets are copied immediately (relative to cwd), so the
                    # target must be the real generation block directory.
                    block_dir = ctx.generation_path / self.get_block_directory_for_phase(phase, block=block)
                    source_list:list[str] = []
                    build_path = self.get_block_path_for_phase(phase, block=block, suffix="-build.pkr.hcl")

                    items.append(Asset((build_path, "# Build configuration for Packer "
                                "EBS Ansible Builder generated by "
                                f"{self.__class__.__name__} ({self.name})")))
                    block_list = block_map.get(block, [])
                    for image in block_list:
                        source_list.append(f'"source.{self.get_packer_source_type()}.{image.get_name()}"')
                        srcpth = self.get_block_path_for_phase(phase,
                            block=block,
                            discriminator= f"source-{image.get_name()}",
                            suffix=".pkr.hcl"
                        )
                        items.add(
                                srcpth,
                                f"# Packer configuration for image {image.get_name()} generated by "
                                f"{self.__class__.__name__} ({self.name})",
                        )
                        # for ib in image.get_im
                        this_runtime = self.model.get_runtime_provider()
                        for s in self.image_to_source(self.get_packer_source_type(), this_runtime, image):
                            items.add(srcpth, s)
                    items.add(build_path, "")
                    if source_list:
                        items.add(build_path, "build {")
                        items.add(build_path, f'  name = "{self.name}-{block}"')
                        items.add(build_path, "  sources = [")
                        log.debug(f"Sources string for build configuration:\n'{",\n".join(source_list)}'")
                        items.add(build_path, ",\n  ".join(source_list))
                        items.add(build_path, "]")
                        # TODO Add mod targets
                        for image in block_list:
                            if isinstance(image, BaseImage):
                                # Base images receive no modification elements —
                                # at most the OS-provided package-level update.
                                if getattr(image, "modifications", None):
                                    log.warning(f"Base image {image.get_name()} carries "
                                                "modifications; base images do not receive "
                                                "modifications — ignoring them")
                                osb = ctx.os_builders.get(image.get_name(), None)
                                if osb is None:
                                    log.warning(f"No OS builder found for base image "
                                                f"{image.get_name()}; skipping OS update")
                                else:
                                    items.extend(osb.generate_items_for_os_update(
                                        image, self, phase, build_path))
                                # V2 (§3F1/N9): admin user, declared-type
                                # prerequisites (dormant) and the session agent.
                                from .v2_provisioners import base_image_provisioners
                                items.add_list(build_path, base_image_provisioners(
                                    ctx, image, self.get_packer_source_type(),
                                    self.model.get_runtime_provider()))
                                # EXPLORE image tests: verification is the LAST step
                                # (bar the runtime's bake finalization, finding 47).
                                from cs_image_system.base.image_tests import (
                                    base_image_verify_commands, finalize_provisioner, verify_provisioner)
                                items.add_list(build_path, verify_provisioner(
                                    f"{self.get_packer_source_type()}.{image.get_name()}",
                                    base_image_verify_commands(ctx, image, self.model.get_runtime_provider()),
                                    f"base image {image.get_name()}"))
                                items.add_list(build_path, finalize_provisioner(
                                    ctx, f"{self.get_packer_source_type()}.{image.get_name()}",
                                    self.model.get_runtime_provider(), None))
                                continue
                            for _mod in image.modifications:
                                mod:ModItemModel = cast(ModItemModel, _mod)
                                # Get the mod builder for mod
                                mbb = ctx.mod_builders.get(mod.get_type(), None)
                                assert mbb is not None, f"No mod builder {mod.get_type()} found in context for {image.get_name()}"
                                copied_assets = mbb.copy_external_assets(block_dir, mod) # Ensure any external assets
                                # MUTATES THE MOD!!!!
                                mod.remap_self_with_copied_assets(copied_assets) # are copied and the mod item is remapped to point to the copied assets
                                # have the mod builder append strings
                                i = mbb.generate_items_before_modification(image, mod, self, phase, build_path)
                                if i: items.extend(i)
                                i = mbb.generate_items_during_modification(image, mod, self, phase, build_path)
                                if i: items.extend(i)
                                i = mbb.generate_items_after_modification(image, mod, self, phase, build_path)
                                if i: items.extend(i)
                                # TODO Add writing of provisioning playbook files in write_specific_files
                            # V2 (§3F2): activation for the image's OWN owning
                            # group, after its modifications, overwriting the
                            # parent image's activation.
                            from .v2_provisioners import instance_image_provisioners
                            items.add_list(build_path, instance_image_provisioners(
                                ctx, image, self.get_packer_source_type()))
                            # EXPLORE local mods: install this bake's modifications
                            # on the image (/opt/csis/mods + csis-mods runner).
                            from .v2_local_mods import stage_local_mods
                            items.add_list(build_path, stage_local_mods(
                                ctx, image, block_dir, f"{self.get_packer_source_type()}.{image.get_name()}"))
                            # EXPLORE image tests: verification is the LAST step
                            # (bar the runtime's bake finalization, finding 47).
                            from cs_image_system.base.image_tests import (
                                finalize_provisioner, instance_image_verify_commands, verify_provisioner)
                            items.add_list(build_path, verify_provisioner(
                                f"{self.get_packer_source_type()}.{image.get_name()}",
                                instance_image_verify_commands(ctx, image),
                                f"instance image {image.get_name()}"))
                            items.add_list(build_path, finalize_provisioner(
                                ctx, f"{self.get_packer_source_type()}.{image.get_name()}",
                                self.model.get_runtime_provider(), None))
                            # for s in image_to_build_target(self.get_packer_source_type(), self, image):
                            #     items.append(Asset((build_path, s + "")))
                        # Record built artifact ids so finalization can resolve
                        # provider-specific images to the exact AMIs of this run.
                        items.add_list(build_path, [
                            '  post-processor "manifest" {',
                            f'    output     = "{MANIFEST_FILENAME}"',
                            "    strip_path = true",
                            "  }",
                        ])
                        items.add(build_path, "}")
        return items

    def post_finalize_phase(self, phase: ExecutionLifecyclePhase) -> None:
        """After this builder's packer builds ran, resolve PSIs from manifests.

        Each block dir contains a packer manifest recording the artifacts of the
        run; every built image's ProviderSpecificImage is upgraded from deferred
        (name-pattern) to resolved (concrete AMI id) so downstream consumers
        (e.g. the instance terraform) can pin the exact artifact.
        """
        if phase != ExecutionLifecyclePhase.IMAGE_GENERATION:
            return
        ctx = GlobalTypeContext()
        rtb = ctx.runtime_builders.get(self.model.get_runtime_provider(), None)
        if rtb is None:
            log.warning(f"No runtime builder for {self.get_display_name()}; "
                        "cannot resolve built images from manifests")
            return
        blocks, block_map = self.get_blocks()
        images_by_name: dict[str, Image | BaseImage] = {
            img.get_name(): img for imgs in block_map.values() for img in imgs}
        built: dict[str, str] = {}
        for block in blocks:
            manifest = (ctx.generation_path
                        / self.get_block_directory_for_phase(phase, block=block)
                        / MANIFEST_FILENAME)
            for image_name, ami in parse_packer_manifest(manifest, rtb).items():
                log.info(f"Built image {image_name} -> {ami} (from {manifest})")
                rtb.create_provider_specific_image_resolved(
                    source_name=image_name,
                    source_kind=PSISourceKind.IMAGE,
                    identifier=ami,
                    owner=SELF,
                )
                built[image_name] = ami
        # Lineage (DESIGN §3F4, N11, N23c): record every built artifact with
        # its stamp and mods; first-bind parent edges for images whose parent
        # was built this run.
        from cs_image_system.base.lineage import record_build

        def _resolve_parent(series: str) -> str | None:
            if series in built:
                return built[series]
            psi = ctx.get_provider_specific_image(series, rtb.get_name())
            return psi.identifier if psi is not None and psi.is_resolved() else None

        from cs_image_system.base.lineage import TAG_PREFIX
        for image_name, ami in built.items():
            image = images_by_name.get(image_name)
            if image is None:
                continue
            subconfig = image.get_image_runtime_subconfig_for_runtime(rtb.get_name())
            name = self._final_name(subconfig) if subconfig is not None else None
            record = record_build(ctx, image, rtb.get_name(), ami, name, _resolve_parent)
            # zero-drift-report: a parent resolved only after its bake leaves
            # generation-time `series:<name>`/stale-fingerprint tags on the
            # AMI. Lineage now holds the resolved truth; stamp it back
            # unconditionally -- create-tags is idempotent, and no detection
            # heuristic can be wrong.
            if record:
                rtb.retag_image(ami, {
                    f"{TAG_PREFIX}parent": str(record.get("parent", "")),
                    f"{TAG_PREFIX}fingerprint": str(record.get("input_fingerprint", ""))[:16],
                })

    def get_commands_to_run_after(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run after a specific execution lifecycle event."""
        commands_now: list[ExecutableModel] = []
        commands_final: list[ExecutableModel] = []
        if  phase == ExecutionLifecyclePhase.IMAGE_GENERATION:
            blocks, block_map = self.get_blocks()
            for block in blocks:
                wd = self.get_block_path_for_phase(phase, block=block, suffix=".tf").parent
                assert wd is not None, (
                    f"Working directory for commands to run after {phase.value} cannot be "
                    f"None for builder {self.__class__.__name__}"
                )
                for cmd in [["fmt", "."], ["init", "."], ["validate","."]]:
                    e = self.get_executable_copy()
                    if not e:
                        raise ValueError(
                            f"Executable for {self.__class__.__name__} is not available "
                            f"but is required to run commands after {phase.value}"
                        )
                    e.args = cmd
                    e.working_directory = wd
                    commands_now.append(e)
                e = self.get_executable_copy()
                e.args = [
                    "build",
                    ".",
                ]  # This is the command that actually does the image building, so we put
                # it in the "after" list to run after all the setup and validation commands.
                e.working_directory = wd
                commands_final.append(e)
        return CFExecutables(commands_now, commands_final)

    @staticmethod
    def _final_name(subconfig) -> str | None:
        """The unique artifact name (DESIGN §3F4): the subconfig's templated
        final name with the run's execution values rendered. The
        ``execution.timestamp`` template never resolved through the field
        resolver (it is not a registered object), so it is rendered here."""
        name = subconfig.get_final_name() if subconfig is not None else None
        if not name:
            return name
        if "{{" in name:
            import jinja2
            ctx = GlobalTypeContext()
            dtfmt = getattr(ctx.read_config, "dateformat", None) or "%Y%m%d_%H%M%S"
            execution = {
                "timestamp": ctx.start_time.strftime(dtfmt),
                "date": ctx.start_time.date().isoformat(),
                "dateformat": dtfmt,
            }
            name = jinja2.Template(name).render(execution=execution)
        return name

    def get_blocks(self) -> tuple[list[str], dict[str, list[Image|BaseImage]]]:
        """Determine blocks of images that can be built together based on their dependencies.

        Under the V2 meta-workflow the current lifecycle selects the images:
        the base-image lifecycle builds only os-builder base images, the
        instance-image lifecycle only user images. With no lifecycle current
        (legacy flow) both ranges are emitted, base images first.
        """
        from cs_image_system.base.lifecycles import Lifecycle
        lifecycle = GlobalTypeContext().current_lifecycle
        blocks: list[str] = []
        block_map: dict[str, list[Image|BaseImage]] = {}
        images:list[Image|BaseImage] = (self.get_images(os_builder=True)  # type: ignore
                                        if lifecycle in (None, Lifecycle.BASE_IMAGE) else [])
        if images:
            # The first range of images is unaffected by the second range
            new_blocks, new_block_map = self.order_blocks_from_images(images)
            blocks.extend(new_blocks)
            for k,v in new_block_map.items():
                block_map.setdefault(k, []).extend(v)
        images = (self.get_images(os_builder=False)
                  if lifecycle in (None, Lifecycle.INSTANCE_IMAGE) else [])
        if images:
            # The second range of images must start after the first
            # So we jump the index by the number of blocks
            new_blocks, new_block_map = self.order_blocks_from_images(images, index_jump=len(blocks))
            blocks.extend(new_blocks)
            for k,v in new_block_map.items():
                block_map.setdefault(k, []).extend(v)
        return blocks, block_map

    def fetch_image_dependency_graph(self,images: list[Image|BaseImage]) -> dict[str, set[str]]:
        """Build the dependency graph for a list of images.

        Parameters
        ----------
        images : List[Image]
            Image objects to analyze for source-image dependencies.

        Returns
        -------
        Dict[str, Set[str]]
            Mapping of image names to their dependency names.
        """
        graph: dict[str, set[str]] = {image.get_name(): set() for image in images}
        # Ensure default is always present as a base image with no dependencies.
        # graph[SELF] = set()
        for image in images:
            if image.source_image in graph:
                graph.setdefault(image.get_name(), set()).add(image.source_image)
        return graph

    def fetch_work_list_order(self, graph: dict[str, set[str]]) -> list[set[str]]:
        """Fetch the work list order based on the image dependency graph.

        Parameters
        ----------
        graph : Dict[str, Set[str]]
            Mapping of image names to the image names they depend on.

        Returns
        -------
        List[Set[str]]
            Sets of image names, ordered by execution stage.
            Images inside the same set can run in parallel.
        """
        workset: dict[str, set[str]] = {}
        DEFAULT_KEY = "###"
        work_list: list[str] = [DEFAULT_KEY]
        # FIXME I'll bet there's a better way to do this...
        try:
            ts = TopologicalSorter(graph)
            for work_piece in ts.static_order():
                work_set = {work_piece} if isinstance(work_piece, str) else set(work_piece)
                for _work_item in work_set:
                    dep = graph[work_piece] if graph[work_piece] else DEFAULT_KEY
                    for d in dep:
                        if d not in work_list:
                            work_list.append(d)
                        workset.setdefault(d, set()).update(work_set)  # type: ignore
        except Exception as e:
            log.error(f"Error during topological sort of images: {e}")
            raise e
        retval =  [workset[k] for k in work_list if k in workset]
        return retval



    def order_blocks_from_images(self, images: list[Image|BaseImage], index_jump: int = 0) -> tuple[list[str], dict[str, list[Image|BaseImage]]]:
        _blocks: list[str] = []
        _block_map: dict[str, list[Image|BaseImage]] = {}

        image_map: dict[str, Image|BaseImage] = {image.get_name(): image for image in images}

        wlo: list[set[str]] = self.fetch_work_list_order(
                self.fetch_image_dependency_graph(images)
            )
        for idx, work_set in enumerate(wlo):
                _block_name = f"block-{idx+index_jump:03d}"
                _blocks.append(_block_name)
                # Sorted: work sets are Python sets, whose iteration order
                # changes per process (hash randomization); deterministic source
                # order keeps the generated build files reviewable.
                for image_name in sorted(work_set):
                    image = image_map.get(image_name, None)
                    if image:
                        _block_map.setdefault(_block_name, []).append(image)
                    else:
                        _block_map[_block_name] = []
        return _blocks, _block_map

    def generate_items_after(self,
                             phase: ExecutionLifecyclePhase) -> AssetSet:
        items = AssetSet()
        # ctx = GlobalTypeContext()
        # build_path = self.get_path_for_phase(phase, suffix="-build.pkr.hcl")
        # if phase == ExecutionLifecyclePhase.DEFAULT_IMAGE_RESOLUTION:
        #     source_list:list[str] = []
        #     images:list[Image] = self.get_images(os_builder=True)
        #     if images:
        #         items.append((build_path, "# Build configuration for Packer EBS Ansible Builder generated by "
        #                     f"{self.__class__.__name__} ({self.name})"))
        #     for image in images:
        #         source_list.append(f'"source.amazon-ebs.{image.name}"')
        #         srcpth = self.get_path_for_phase(
        #             phase, f"source-{image.name}", suffix=".pkr.hcl"
        #         )
        #         items.append(
        #             (
        #                 srcpth,
        #                 f"# Packer configuration for image {image.name} generated by "
        #                 f"{self.__class__.__name__} ({self.name})",
        #             )
        #         )
        #         for s in image_to_source(self.get_packer_source_type(), self, image):
        #             items.append((srcpth, s + ""))
        #     items.append((build_path, ""))
        #     items.append((build_path, "build {sources = ["))
        #     sources_str = ",".join(source_list)
        #     items.append((build_path, f"  {sources_str},"))
        #     items.append((build_path,"]"))
        #     #  Add mod targets

        #     for image in images:
        #         for mod in image.modifications:
        #             mb = ctx.mod_builders.get(mod.type_, None)
        #             assert mb is not None, "No mod builders found in context."
        #             mb_items = mb.generate_items_before_modification(image,
        #                                                              mod,
        #                                                              self,
        #                                                              phase)
        #     for image in images:
        #         for mod in image.modifications:
        #             mb = ctx.mod_builders.get(mod.type_, None)
        #             assert mb is not None, "No mod builders found in context."
        #             mb_items = mb.generate_items_during_modification(image,
        #                                                              mod,
        #                                                              self,
        #                                                              phase,
        #                                                              build_path)
        #     for image in images:
        #         for mod in image.modifications:
        #             mb = ctx.mod_builders.get(mod.type_, None)
        #             assert mb is not None, "No mod builders found in context."
        #             mb_items = mb.generate_items_after_modification(image,
        #                                                  mod,
        #                                                  self,
        #                                                  phase,
        #                                                  build_path)
        #     items.append((build_path, "}"))
        return items


    def image_to_source(self, type: str, runtime: str, image: Image|BaseImage) -> list[str]:
        """Convert an Image object to a list of packer 'source' lines for use in builds."""
        ctx = GlobalTypeContext()
        rtb = ctx.runtime_builders.get(self.model.runtime)
        assert rtb is not None, (
            f"Runtime builder must be available to convert image {image.name} "
            "to source configuration."
        )

        tags = copy.deepcopy(image.get_tags() or {})
        irtsc = image.get_image_runtime_subconfig_for_runtime(runtime)
        if not irtsc:
            raise ValueError(
                f"Image {image.name} does not have runtime-specific data for runtime "
                f"{runtime} required to convert to source configuration."
            )
        tags.update(irtsc.get_tags() or {})
        # Locate the provider-specific image for this image's source: the image's
        # own PSI when it builds from SELF (os-resolved base images, registered
        # during the resolution phase), otherwise the PSI of the source image it
        # chains from (resolved for base images, deferred for user images that a
        # prior block builds).
        source_ref = (image.source_image
                      if image.source_image and image.source_image != SELF
                      else image.get_name())
        psi = ctx.get_provider_specific_image(source_ref, runtime)
        if psi is None:
            errstr = (
                f"No provider-specific image registered for source {source_ref!r} "
                f"of image {image.name} on runtime {runtime}; cannot convert to "
                "source configuration."
            )
            log.error(errstr)
            raise ValueError(errstr)
        log.debug(f"Provider-specific image for {image.get_display_name()} on runtime "
                  f"{runtime}: {psi.state.value}")


        # # osrb = ctx.os_builders.get(image.os) if image.os else None
        # # if image.os and not osrb:
        # #     raise ValueError(
        # #         f"Image {image.name} has OS {image.os} but no OS builder is "
        # #         "configured in context to convert to source configuration."
        # #     )
        # osrtscp = osrb.get_configs_for_runtimes()[rtb.get_name()] if osrb else None
        # if osrb and not osrtscp:
        #     raise ValueError(
        #         f"OS builder for image {image.name} does not have a runtime configuration "
        #         f"for runtime {rtb.get_name()} required to convert to source configuration."
        #     )
        # image_id = osrtscp.get_image_id_for_runtime() if osrtscp else None
        # if not irtsc.image_identifier:
        #     err = (
        #         f"Image {image.name} does not have a valid image identifier in its "
        #         f"runtime-specific data for runtime {runtime} required to convert to "
        #         "source configuration."
        #     )
        #     log.error(err)
        #     raise ValueError(err)

        self_rtc = image.get_image_runtime_subconfig_for_runtime(runtime)
        if not self_rtc:
            raise ValueError(
                f"Image {image.name} does not have runtime-specific data for runtime "
                f"{runtime} required to convert to source configuration."
            )
        final_name = self._final_name(self_rtc)
        if not final_name:
            raise ValueError(
                f"Image {image.name} does not have a valid output image name in its "
                f"runtime-specific data for runtime {runtime} required to convert to "
                "source configuration."
            )
        from cs_image_system.base.lineage import lineage_tags, pinned_parent_build
        tags.update(lineage_tags(ctx, image, runtime))
        # N17: a rebuild bakes FROM its pinned base build (an image-id filter),
        # never a most-recent lookup; unpinned images bind at first bake.
        pinned = pinned_parent_build(ctx, image, runtime)
        if pinned:
            log.info(f"Image {image.get_name()} bakes from pinned build {pinned}")
        # Provider-neutral from here (EXPLORE GCP increment 1): the runtime
        # plugin emits the source block for ITS packer plugin.
        return rtb.packer_source_blocks(
            image, runtime=runtime, source_type=type, subconfig=irtsc, self_subconfig=self_rtc,
            psi=psi, tags=tags, final_name=final_name, pinned=pinned)


    # source "amazon-ebs" "rhel8-10" {
    #   ami_name      = "${var.base_image_name}-rhel8.10-${local.image_version}"
    #   instance_type = var.instance_type
    #   region        = var.aws_region
    #   #   source_ami    = var.source_ami
    #   ssh_username     = var.ssh_username
    #   ssh_keypair_name     = var.keypair
    #   ssh_private_key_file = var.keypairfile
    #   vpc_id           = var.vpc_id
    #   subnet_id        = var.subnet_id
    #   force_deregister = !var.release

    #   launch_block_device_mappings {
    #     device_name           = "/dev/sda1"
    #     volume_size           = 60
    #     volume_type           = "gp3"
    #     delete_on_termination = true
    #   }

    #   source_ami_filter {
    #     filters = {
    #       name                = var.rhel8_10_search_name
    #       root-device-type    = "ebs"
    #       virtualization-type = "hvm"
    #       architecture        = "x86_64"
    #     }
    #     owners      = [var.rhel8_owner] # Red Hat's AWS account ID
    #     most_recent = true
    #   }

    #   tags = {
    #     Name        = "${var.base_image_name}-RHEL8.10"
    #     Version     = var.base_image_version
    #     Environment = "Production"
    #     CreatedBy   = "Packer"
    #     Role        = "Base Image RHEL 8.10"
    #   }
    # }


class PackerGceImageBuilder(PackerEbsImageBuilder):
    """The packer builder bound to a GCE runtime (EXPLORE GCP increment
    2). Everything provider-specific comes from the runtime plugin's packer
    hooks; this class exists so configuration can say ``type: packer-gce``."""

    @classmethod
    def csis_name(cls) -> str:
        from .packer_models import PACKER_GCE
        return PACKER_GCE
