# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""``generated/bootstrap/`` from ``bootstrap.yaml``: regenerated by the
``bootstrap`` command and by every run (generation only, before the
lifecycles), pruned when the answers file is absent -- the same wipe-and-
regenerate rule as a lifecycle's directory, and the same ``.gitignore``
policy (tool residue, plans and state out; the tfvars and everything else
in)."""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable

from .answers import ANSWERS_FILE, read_answers
from .facts import raw_yaml
from .hcl import render_root
from .questions import Rendered, Section

if TYPE_CHECKING:
    from ..global_context import GlobalTypeContext

log = logging.getLogger(__name__)

BOOTSTRAP_DIRNAME = "bootstrap"
GITIGNORE = """# Tool residue and state stay out; the tfvars and everything else are committed (decision D3)
.terraform/
!.terraform.lock.hcl
*.tfstate
*.tfstate.*
tfplan
!bootstrap.auto.tfvars
"""


def output_dir(config_root: Path) -> Path:
    return Path(config_root) / "generated" / BOOTSTRAP_DIRNAME


def module_source_base_of(config_root: Path) -> str:
    """The tree's ``module_source_base`` from the raw ``cfg/_config.yml``
    (``tfmodules`` when unset), as the lifecycles read it -- without loading."""
    config = raw_yaml(Path(config_root) / "cfg" / "_config.yml").get("config")
    if isinstance(config, dict) and config.get("module_source_base"):
        return str(config["module_source_base"])
    return "tfmodules"


def module_source_for(config_root: Path, module_source_base: str) -> str:
    """The module source prefix as written from ``generated/bootstrap``: a
    relative base is relative to the config root (as it is for the
    lifecycles' roots, four levels deep; this one is two), so it is
    re-rooted; an absolute path, a URL or a registry address passes."""
    base = module_source_base.rstrip("/")
    if base.startswith("/") or "://" in base or base.startswith(("git@", "github.com/")):
        return base
    if not base.startswith("."):
        base = f"./{base}"
    target = (Path(config_root) / base).resolve()
    return os.path.relpath(target, output_dir(config_root).resolve()).replace(os.sep, "/")


def prune(config_root: Path) -> bool:
    out = output_dir(config_root)
    if out.exists():
        shutil.rmtree(out)
        return True
    return False


def render_files(sections: Iterable[Section], answers: dict[str, dict[str, Any]], *,
                 module_source: str) -> dict[str, str]:
    by_name = {s.name: s for s in sections}
    rendered: dict[str, Rendered] = {}
    repository: str | None = None
    secrets_dir: str | None = None
    for name, section_answers in sorted(answers.items()):
        if not section_answers.get("wanted"):
            continue
        section = by_name.get(name)
        if section is None:
            log.warning(f"bootstrap: section {name!r} is answered in {ANSWERS_FILE} but no installed plugin "
                        "offers it; its answers are kept and it contributes nothing")
            continue
        rendered[name] = section.render(section_answers)
        if name == "github":
            repository = str(section_answers.get("repository") or "") or None
            secrets_dir = str(section_answers.get("secrets_dir") or "") or None
    return render_root(rendered, module_source_base=module_source, repository=repository, secrets_dir=secrets_dir)


def regenerate(config_root: Path, *, module_source_base: str | None = None,
               sections: Iterable[Section] | None = None) -> list[Path] | None:
    """Rewrite ``generated/bootstrap/`` from ``bootstrap.yaml``; None (and the
    directory pruned) when there is no answers file. Returns the paths
    written, the ``.gitignore`` included."""
    root = Path(config_root)
    answers_path = root / ANSWERS_FILE
    if not answers_path.is_file():
        if prune(root):
            log.info(f"bootstrap: no {ANSWERS_FILE} in the tree; generated/{BOOTSTRAP_DIRNAME} pruned")
        return None
    if sections is None:
        from .sections import discover
        sections = discover()
    answers = read_answers(answers_path)
    base = module_source_base or module_source_base_of(root)
    files = render_files(sections, answers, module_source=module_source_for(root, base))
    out = output_dir(root)
    prune(root)
    out.mkdir(parents=True)
    written: list[Path] = []
    for name, text in sorted(files.items()):
        p = out / name
        p.write_text(text)
        if name.endswith(".sh"):
            p.chmod(0o755)
        written.append(p)
    (out / ".gitignore").write_text(GITIGNORE)
    written.append(out / ".gitignore")
    return written


def regenerate_in_run(ctx: "GlobalTypeContext") -> None:
    """Inside every run, before the lifecycles (stage 70, decision D7)."""
    root = Path(ctx.working_path)
    base = None
    try:
        base = ctx.config.get("module_source_base")
    except Exception:
        base = None
    written = regenerate(root, module_source_base=str(base) if base else None)
    if written:
        log.info(f"bootstrap: generated/{BOOTSTRAP_DIRNAME} regenerated from {ANSWERS_FILE} "
                 f"({len(written)} files; generation only, never applied by a run)")
