# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""``generated/bootstrap/`` from ``bootstrap.yaml``: regenerated by the
``bootstrap`` command and by every run (generation only, before the
lifecycles), pruned when the answers file is absent, under the lifecycles'
``.gitignore`` policy (tool residue, plans and state out; the tfvars and
everything else in). One difference from a lifecycle's directory, which is
wiped whole: what a person's own ``tofu`` left here is never deleted -- the
provider directory, the lock, a saved plan, and the state of a root still
on the local backend."""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable

from .answers import ANSWERS_FILE, read_answers
from .facts import raw_yaml
from .hcl import render_root
from .questions import Rendered, Section

if TYPE_CHECKING:
    from ..global_context import GlobalTypeContext

log = logging.getLogger(__name__)

BOOTSTRAP_DIRNAME = "bootstrap"
GITIGNORE = """# Tool residue and state stay out; the tfvars and everything else are committed (decision D3)
.terraform/
!.terraform.lock.hcl
*.tfstate
*.tfstate.*
tfplan
!bootstrap.auto.tfvars
"""


def output_dir(config_root: Path) -> Path:
    return Path(config_root) / "generated" / BOOTSTRAP_DIRNAME


def module_source_base_of(config_root: Path) -> str:
    """The tree's ``module_source_base`` from the raw ``cfg/_config.yml``
    (``tfmodules`` when unset), as the lifecycles read it -- without loading."""
    config = raw_yaml(Path(config_root) / "cfg" / "_config.yml").get("config")
    if isinstance(config, dict) and config.get("module_source_base"):
        return str(config["module_source_base"])
    return "tfmodules"


def module_source_for(config_root: Path, module_source_base: str) -> str:
    """The module source prefix as written from ``generated/bootstrap``: a
    relative base is relative to the config root (as it is for the
    lifecycles' roots, four levels deep; this one is two), so it is
    re-rooted; an absolute path, a URL or a registry address passes."""
    base = module_source_base.rstrip("/")
    if base.startswith("/") or "://" in base or base.startswith(("git@", "github.com/")):
        return base
    if not base.startswith("."):
        base = f"./{base}"
    target = (Path(config_root) / base).resolve()
    return os.path.relpath(target, output_dir(config_root).resolve()).replace(os.sep, "/")


#: What a person's own `tofu` leaves in the root, which no run may delete:
#: the provider directory, the dependency lock, a saved plan, and above all
#: the STATE of a root on the local backend (the first apply, before a bucket
#: stands). A lifecycle's directory is wiped and regenerated because its
#: state is remote; this root's may be right here.
PRESERVED_NAMES = (".terraform", ".terraform.lock.hcl", "tfplan")
PRESERVED_GLOBS = ("*.tfstate", "*.tfstate.*")


def preserved(path: Path) -> bool:
    return path.name in PRESERVED_NAMES or any(path.match(g) for g in PRESERVED_GLOBS)


def clear_generated(out: Path) -> list[Path]:
    """Remove what a generation wrote, and nothing a person's tofu left.
    Returns what was kept."""
    kept: list[Path] = []
    for child in sorted(out.iterdir()):
        if preserved(child):
            kept.append(child)
        elif child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()
    return kept


def prune(config_root: Path) -> bool:
    """The answers are gone, so the generated root goes -- but never a state
    file or the tool's own residue: those stay, the directory with them, and
    the log says so. True when something was removed."""
    out = output_dir(config_root)
    if not out.exists():
        return False
    had = any(not preserved(c) for c in out.iterdir())
    kept = clear_generated(out)
    if not kept:
        out.rmdir()
        return True
    if any(k.match("*.tfstate") or k.match("*.tfstate.*") for k in kept):
        log.warning(f"bootstrap: {out} holds terraform STATE ({', '.join(k.name for k in kept)}); the generated "
                    "files are removed but the state is left in place -- it records real resources. Destroy them "
                    "with the answers restored, or move the state away, before removing the directory.")
    return had


def render_files(sections: Iterable[Section], answers: dict[str, dict[str, Any]], *,
                 module_source: str) -> dict[str, str]:
    by_name = {s.name: s for s in sections}
    rendered: dict[str, Rendered] = {}
    repository: str | None = None
    secrets_dir: str | None = None
    for name, section_answers in sorted(answers.items()):
        if not section_answers.get("wanted"):
            continue
        section = by_name.get(name)
        if section is None:
            log.warning(f"bootstrap: section {name!r} is answered in {ANSWERS_FILE} but no installed plugin "
                        "offers it; its answers are kept and it contributes nothing")
            continue
        rendered[name] = section.render(section_answers)
        if name == "github":
            repository = str(section_answers.get("repository") or "") or None
            secrets_dir = str(section_answers.get("secrets_dir") or "") or None
    return render_root(rendered, module_source_base=module_source, repository=repository, secrets_dir=secrets_dir)


def regenerate(config_root: Path, *, module_source_base: str | None = None,
               sections: Iterable[Section] | None = None) -> list[Path] | None:
    """Rewrite ``generated/bootstrap/`` from ``bootstrap.yaml``; None (and the
    directory pruned) when there is no answers file. Returns the paths
    written, the ``.gitignore`` included."""
    root = Path(config_root)
    answers_path = root / ANSWERS_FILE
    if not answers_path.is_file():
        if prune(root):
            log.info(f"bootstrap: no {ANSWERS_FILE} in the tree; generated/{BOOTSTRAP_DIRNAME} pruned")
        return None
    if sections is None:
        from .sections import discover
        sections = discover()
    answers = read_answers(answers_path)
    base = module_source_base or module_source_base_of(root)
    files = render_files(sections, answers, module_source=module_source_for(root, base))
    out = output_dir(root)
    out.mkdir(parents=True, exist_ok=True)
    clear_generated(out)                 # rewrite what generation owns; keep .terraform, the lock, a plan, the state
    written: list[Path] = []
    for name, text in sorted(files.items()):
        p = out / name
        p.write_text(text)
        if name.endswith(".sh"):
            p.chmod(0o755)
        written.append(p)
    (out / ".gitignore").write_text(GITIGNORE)
    written.append(out / ".gitignore")
    return written


def regenerate_in_run(ctx: "GlobalTypeContext") -> None:
    """Inside every run, before the lifecycles (stage 70, decision D7)."""
    root = Path(ctx.working_path)
    base = None
    try:
        base = ctx.config.get("module_source_base")
    except Exception:
        base = None
    written = regenerate(root, module_source_base=str(base) if base else None)
    if written:
        log.info(f"bootstrap: generated/{BOOTSTRAP_DIRNAME} regenerated from {ANSWERS_FILE} "
                 f"({len(written)} files; generation only, never applied by a run)")
