# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""The writer: one root module under ``generated/bootstrap/`` from the
wanted sections' renderings. Deterministic -- the same answers give the same
bytes -- so the root is regenerable and ``config-drift`` can judge it."""

from __future__ import annotations

import json
from typing import Any, Iterable

from .questions import Raw, Rendered, Secret

HEADER = "# Generated by cs-image-system bootstrap from bootstrap.yaml -- do not edit; re-interview or edit the answers.\n"


def tfv(value: Any, indent: int = 0) -> str:
    """An HCL literal: strings quoted (JSON escaping is HCL's), booleans
    lower-case, numbers as is, lists and maps multi-line and sorted."""
    pad = "  " * indent
    if isinstance(value, Raw):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        inner = ",\n".join(f"{pad}  {tfv(v, indent + 1)}" for v in value)
        return f"[\n{inner},\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        width = max(len(json.dumps(str(k))) for k in value)
        lines = [f"{pad}  {json.dumps(str(k)).ljust(width)} = {tfv(v, indent + 1)}" for k, v in sorted(value.items())]
        return "{\n" + "\n".join(lines) + f"\n{pad}}}"
    return json.dumps(str(value))


def _aligned(pairs: list[tuple[str, str]], indent: int = 1) -> str:
    pad = "  " * indent
    width = max((len(k) for k, _ in pairs), default=0)
    return "".join(f"{pad}{k.ljust(width)} = {v}\n" for k, v in pairs)


def render_root(rendered: dict[str, Rendered], *, module_source_base: str, repository: str | None,
                secrets_dir: str | None) -> dict[str, str]:
    """``{filename: text}`` for the root: main.tf, providers.tf, variables.tf,
    outputs.tf, bootstrap.auto.tfvars, set-secrets.sh, README.md."""
    files: dict[str, str] = {}
    sections = sorted(rendered.items())

    # providers.tf: terraform settings, the backend, the provider blocks
    required: dict[str, dict[str, str]] = {}
    for _, r in sections:
        required.update(r.required_providers)
    req = "".join(f"    {name} = {{\n      source  = {json.dumps(spec['source'])}\n      version = {json.dumps(spec['version'])}\n    }}\n"
                  for name, spec in sorted(required.items()))
    providers = HEADER + "terraform {\n  required_version = \">= 1.6\"\n"
    if req:
        providers += "  required_providers {\n" + req + "  }\n"
    providers += ("  # Local state for the first apply (decision D8): the bootstrap may be what\n"
                  "  # makes the state bucket. Once a bucket stands, move this root's state to it\n"
                  "  # (README.md, \"Afterwards\"); terraform.tfstate never enters a commit.\n"
                  "  backend \"local\" {}\n}\n")
    for _, r in sections:
        if r.provider_blocks:
            providers += "\n" + r.provider_blocks
    files["providers.tf"] = providers

    # main.tf: one module call per section
    main = HEADER
    for name, r in sections:
        if not r.module:
            continue
        pairs = [("source", json.dumps(f"{module_source_base.rstrip('/')}/{r.module}"))]
        pairs += [(k, tfv(v, 1)) for k, v in sorted(r.module_args.items())]
        main += f"\nmodule \"{r.module}\" {{\n" + _aligned(pairs) + "}\n"
    files["main.tf"] = main

    # variables.tf
    variables = HEADER
    for _, r in sections:
        for vname, vtype, desc in r.variables:
            variables += f"\nvariable \"{vname}\" {{\n  type        = {vtype}\n  description = {json.dumps(desc)}\n}}\n"
    files["variables.tf"] = variables

    # outputs.tf
    outputs = HEADER
    for _, r in sections:
        for oname, expr, desc in r.outputs:
            outputs += f"\noutput \"{oname}\" {{\n  value       = {expr}\n  description = {json.dumps(desc)}\n}}\n"
    files["outputs.tf"] = outputs

    # bootstrap.auto.tfvars: every answer that feeds a variable
    tfvars: dict[str, Any] = {}
    for _, r in sections:
        tfvars.update(r.tfvars)
    body = _aligned([(k, tfv(v, 0)) for k, v in sorted(tfvars.items())], indent=0)
    files["bootstrap.auto.tfvars"] = (
        "# Generated by cs-image-system bootstrap from bootstrap.yaml -- do not edit here: the\n"
        "# answers file is the source and the next run rewrites this. Committed on purpose\n"
        "# (decision D3): it holds names and ids, never a secret value.\n" + body)

    # set-secrets.sh
    secrets: list[Secret] = []
    seen: set[str] = set()
    for _, r in sections:
        for s in r.secrets:
            if s.name not in seen:
                seen.add(s.name)
                secrets.append(s)
    files["set-secrets.sh"] = _secrets_script(secrets, repository=repository, secrets_dir=secrets_dir)

    # README.md
    files["README.md"] = _readme(sections, secrets, repository=repository)
    return files


def _secrets_script(secrets: Iterable[Secret], *, repository: str | None, secrets_dir: str | None) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by cs-image-system bootstrap -- sets this repository's Actions secrets",
        "# (CI_SETUP.md 3.7). No secret VALUE is in this script, the tfvars or the state:",
        "# each is read from a file named after the secret under the secrets directory,",
        "# or from an output of the applied root. Run it from the repository root after",
        "# `tofu apply` in generated/bootstrap, with `gh` logged in.",
        "set -euo pipefail",
        f"REPO=\"${{REPO:-{repository or ''}}}\"",
        f"DIR=\"${{SECRETS_DIR:-{secrets_dir or '_uncommitted/secrets'}}}\"",
        "ROOT=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
        "",
        "from_file() {   # NAME: the file $DIR/NAME holds the value",
        "  if [ ! -s \"$DIR/$1\" ]; then echo \"set-secrets: $DIR/$1 is missing or empty; skipped\" >&2; return 0; fi",
        "  gh secret set \"$1\" --repo \"$REPO\" < \"$DIR/$1\" && echo \"set-secrets: $1 set from $DIR/$1\"",
        "}",
        "from_output() {   # NAME OUTPUT: the applied root's output holds the value",
        "  gh secret set \"$1\" --repo \"$REPO\" --body \"$(tofu -chdir=\"$ROOT\" output -raw \"$2\")\" && echo \"set-secrets: $1 set from output $2\"",
        "}",
        "",
    ]
    for s in secrets:
        if s.comment:
            lines.append(f"# {s.comment}")
        lines.append(f"from_file {s.name}" if s.source == "file" else f"from_output {s.name} {s.detail}")
    lines.append("")
    return "\n".join(lines)


def _readme(sections: list[tuple[str, Rendered]], secrets: list[Secret], *, repository: str | None) -> str:
    out = ["# The bootstrap root", "",
           "Generated by `cs-image-system bootstrap` from `bootstrap.yaml` at the root of this",
           "tree (stage 70). Every run regenerates this directory from the answers file;",
           "nothing here is edited by hand, and no run ever plans or applies it: applying is",
           "the operator's act, below. `bootstrap.auto.tfvars` carries the answers, so the",
           "apply needs nothing typed again; no secret value is in it or in the state.", "",
           "## What it declares", ""]
    for name, r in sections:
        out.append(f"- **{name}**" + (f" (`tfmodules/{r.module}`)" if r.module else ""))
        out.extend(f"  - {n}" for n in r.notes)
    out += ["", "## Apply", "", "```sh",
            "cd generated/bootstrap",
            "tofu init                      # local state for the first apply",
            "tofu plan                      # read it: nothing here is gated by the system",
            "tofu apply",
            "cd ../..",
            "bash generated/bootstrap/set-secrets.sh",
            "```", "", "## By hand, still", ""]
    for _, r in sections:
        out.extend(f"- {line}" for line in r.by_hand)
    out += ["", "## The secrets the script sets", "", "| Secret | From |", "| --- | --- |"]
    for s in secrets:
        out.append(f"| `{s.name}` | {'a file named after it in the secrets directory' if s.source == 'file' else f'the output `{s.detail}`'} |")
    out += ["", "## Afterwards", "",
            "The first apply keeps its state in `terraform.tfstate` here, which `.gitignore`",
            "keeps out of every commit. When the tree's state bucket stands, move this root's",
            "state into it like any other root's (OPERATIONS.md, \"Moving a root's state\"), so",
            "a second apply from another checkout sees what the first did.",
            "", "Then the proofs in CI_SETUP.md 3.8, in order."]
    if repository:
        out.append(f"\nRepository: `{repository}`.")
    return "\n".join(out) + "\n"
