# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""Global constants for cs-image-action."""

from enum import Enum, StrEnum


NAME = "name"
TYPE = "type"
VERBOSE: str = "verbose"
DEFAULT_CONFIG_FILE: str = "./image-actions.yml"
DEFAULT: str = "default"
ALL: str = "ALL" # ALL CAPS 'ALL' is a magic value that means "all groups, everywhere".  Use with caution.  This is basically saying "I don't care about groups, anyone can use it"
SELF = "self"
OOPS_DEFAULTS: list[str | None] = [DEFAULT, None, "",SELF]
SOURCE_MODEL: str = "SourceModel"


RUNTIME_PROVIDER_TYPE: str = "runtime"
CLOUD_PROVIDER_TYPE: str = "cloud_provider"
CONTAINER_PROVIDER_TYPE: str = "container_provider"
STATE_BACKEND_TYPE: str = "state_backend"
S3_TYPE: str = "s3"
STATE_BACKEND_FIELD: str = "state_configuration"

CONFIGURED_OS: str = "configured_os_builders"
CONFIGURED_IMAGE: str = "configured_image_builders"
CONFIGURED_MOD: str = "configured_mod_builders"
CONFIGURED_INSTANCE: str = "configured_instance_builders"
CONFIGURED_RUNTIME: str = "configured_runtime_providers"
CONFIGURED_STORAGE: str = "configured_storage_providers"
CONFIGURED_GROUP: str = "configured_group_builders"
CONFIGURED_USER: str = "configured_user_builders"
ALL_SORTED_BUILDERS: str = "all_sorted_builders"
STATE_SETUPS: str = "state_setups"
DEFAULT_IMAGES_PER_RUNTIME_BUILDER: str = "default_images_per_rtb"

EXECUTABLES: str = "executables"
FORCE: str = "force"
ONLY_PROVIDERS: str = "only_providers"
WORKING_PATH: str = "working_path"
GLOBAL_CONFIG: str = "config"
LIFECYCLE: str = "lifecycle"
CONFIG_FILE: str = "config_file"
GENERATION_PATH: str = "generation_path"
BASE_IMAGES = "base_images"
IMAGES = "images"
STORAGES = "storages"
GROUPS = "groups"
ROOT_GROUP = "root_group"
USERS = "users"
INSTANCES = "instances"
DEFAULT_GITIGNORE_ENTRIES = [
    "# DO NOT EDIT THIS FILE.",
    "# This .gitignore file is auto-generated by cs-image-action.",
    "# It includes default entries to ignore SOME generated files ",
    "# and directories. ",
    "target/",
    ".terraform/",
    "terraform.tfstate",
    "terraform.tfstate.backup",
    "!.terraform.lock.hcl",
]
# stage 49: the private mirror, beside generated/ under the configuration root.
# It holds the plaintext of every value the emission carries as ciphertext, so
# it is never committed: ignored here, refused by path, skipped by the scanner.
PRIVATE_DIRNAME = "_private"
# stage 43: the run-local files a run writes at the top of generated/ and never
# commits -- the emitted root .gitignore names them, the run's commit excludes
# them and drops them from the index where an older tree tracked them (the
# strict state query rewrites the report outside any run, so a tracked copy
# dirtied the checkout after every preflight)
RUN_SUMMARY_FILENAME = "run-summary.json"
STATE_REPORT_FILENAME = "state-report.json"
PACKER_MANIFEST_FILENAME: str = "manifest.json"   # packer's post-processor output, read for the build's artifact id
# Run-local (stage 43, 48.6): what a run writes for itself and never commits -- the summary,
# the state report and packer's manifest (its artifact ids are recorded in lineage; the
# file itself landed in the record once and is noise there). Ignored under generated/.
RUN_LOCAL_FILENAMES: tuple[str, ...] = (RUN_SUMMARY_FILENAME, STATE_REPORT_FILENAME, PACKER_MANIFEST_FILENAME)
SAVED_LOAD_DICT = "_saved_dict_from_load"
ANY_AT_ALL = "ANY_AT_ALL"

INVALID_CONFIG_KEYS = [ "self", "this", "same", "runtime", 
                       "os", "default", "defaults", "any",
                       "anything", "none", "null", "" ,
                       "timestamp", "date", "datetime", 
                       "config", "configuration",]

IS_DEFERRED_LIST_GENERATED = "is_deferred_list_generated"
DEFERRED_BUILDER_VCT = "deferred_builder_vct"
DEFERRED_ITEM_VCT = "deferred_item_vct"
FK_ALSO_SET_ON_UPDATE = "fk_also_set_on_update"
IS_DEFERRED_LIST_FK = "is_deferred_list_fk"
IS_FK = "is_fk"
FK_TARGET = "fk_target"
IS_REPLACE = "is_replace"
REPLACE_VALUE = "replace_value"
# Open discriminator: names a field's late-binding "kind" (see helpers/field_kinds.py).
# Derived from the legacy boolean flags above when absent; plugins may set it
# explicitly to register a brand-new kind + handler.
FIELD_KIND = "field_kind"

NO_MODEL_ID = "__NoParentModel__"
UNSET_MODEL_ID = "__UNSETMODELID__"
class VCT(StrEnum):
    """Enum for valid classification types."""
    UNCLASSIFIED = "__NMC__"
    RUNTIME_BUILDER_MODEL = "runtime_builder_model"
    RUNTIME_BUILDER = "runtime_builder"
    CLOUD_BUILDER_MODEL = "cloud_builder_model"
    CLOUD_BUILDER = "cloud_builder"
    CONTAINER_BUILDER_MODEL = "container_builder_model"
    CONTAINER_BUILDER = "container_builder"
    USER_BUILDER_MODEL = "user_builder_model"
    USER_BUILDER = "user_builder"
    GROUP_BUILDER_MODEL = "group_builder_model"
    GROUP_BUILDER = "group_builder"
    OS_BUILDER_MODEL = "os_builder_model"
    OS_BUILDER = "os_builder"
    OS_IMAGE_BUILDER_SUBCONFIG = "os_image_builder_subconfig"
    OS_IMAGE_BUILDER_SUBCONFIG_MODEL = "os_image_builder_subconfig_model"
    IMAGE_BUILDER_MODEL = "image_builder_model"
    IMAGE_BUILDER = "image_builder"
    IMAGE_IMAGE_BUILDER_SUBCONFIG_MODEL = "image_image_builder_subconfig_model"
    STORAGE_MAPPING_ITEM_MODEL = "storage_mapping_item_model"
    MOD_BUILDER_MODEL = "mod_builder_model"
    MOD_BUILDER = "mod_builder"
    MOD_BUILDER_ITEM_MODEL = "mod_builder_item_model"
    INSTANCE_BUILDER = "instance_builder"
    INSTANCE_BUILDER_MODEL = "instance_builder_model"
    STORAGE_BUILDER = "storage_builder"
    STORAGE_BUILDER_MODEL = "storage_builder_model"
    STATE_BACKEND = "state_backend"
    STATE_BACKEND_MODEL = "state_backend_model"
    EXECUTABLE_MODEL = "executable_model"
    VERSION_CHECKER = "version_checker"
    BASE_IMAGE_MODEL = "base_image_model"
    IMAGE_MODEL = "image_model"
    INSTANCE_MODEL = "instance_model"
    GROUP_MODEL = "group_model"
    USER_MODEL = "user_model"
    STORAGE_MODEL = "storage_model"
    MOD_MODEL = "mod_model"    
    SOURCE_MODEL_MODEL = "source_model_model"
    RESOLVED_IMAGE_MODEL = "resolved_image_model"
    PROVIDER_SPECIFIC_IMAGE = "provider_specific_image"


PLUGIN_TYPES: list[tuple[str, str]] = [
    ("base", "base_plugins"),
    ("runtime", "runtime_builders"),
    ("state", "state_backends"),
    ("modification", "mod_builders"),
    ("storage", "storage_builders"),
    ("group", "group_builders"),
    ("user", "user_builders"),
    ("image", "image_builders"),
    ("os", "os_builders"),
    ("instance", "instance_builders"),
    ("other", "other_builders"),
    # ("executables", "executables")
]
class OSFamilies(StrEnum):
    """
    Enum for OS family classification.
    These are the valid keys for os-family designations

    """

    RHEL = "rhel"
    UBUNTU = "ubuntu"
    DEBIAN = "debian"
    FEDORA = "fedora"
    OPENSUSE = "opensuse"
    SUSE = "suse"
    ROCKYLINUX = "rocky-linux"
    ALMALINUX = "alma-linux"
    CENTOS = "centos"
    CENTOS_STREAM = "centos-stream"


class ComplianceState(Enum):
    """Enum for compliance state classification."""

    IGNORED = "ignored"
    ACCEPTABLE = "acceptable"
    UNACCEPTABLE = "unacceptable"
