# Terraform module call for storage efs-storage generated by TofuEfsStorageBuilder (aws-efs)
# allowed groups: coops, stofs (gids by remote-state reference); public_read=false; requested state: active
module "storage_efs_storage" {
  source = "../../../../../tfmodules/aws_storage_efs"
  providers = { aws = aws.aws_efs }
  name = "efs-storage"
  access_points = {
    "coops" = {
      "gid" = data.terraform_remote_state.oktagroups.outputs.group_gids["coops"]
      "path" = "/coops"
      "permissions" = "2775"
    }
    "stofs" = {
      "gid" = data.terraform_remote_state.oktagroups.outputs.group_gids["stofs"]
      "path" = "/stofs"
      "permissions" = "2775"
    }
  }
}
output "storage_efs_storage" {
    value = module.storage_efs_storage
    description = "Outputs of storage efs-storage for remote-state consumers"
}