# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

from functools import partial
import logging
from typing import Any

from cs_image_system.base import utils
from cs_image_system.base.basic.asset import AssetSet
from cs_image_system.base.basic.builder_base_user import UserBuilderBase
from cs_image_system.base.constants import USERS
from cs_image_system.base.lifecycle import ExecutionLifecyclePhase
from cs_image_system.base.models.executable_adds import CFExecutables
from cs_image_system.base.models.user import User
from cs_image_system.hashicorp_utils.collector import TerraformCollector
from cs_image_system.hashicorp_utils.roots import TerraformRootMixin

from .okta_opa_tf_user_models import OktaTfUserBuilderModel
from .opa_attributes import OPA_USER_ATTRIBUTES, validate_opa_attributes
from .opa_gids import OpaGidResolver, credentials_from_env
from .okta_tf_models import OKTATF, OktaTFUser
from .okta_tf_workspace import OKTA_PROVIDER, okta_credentials_present

log = logging.getLogger(__name__)


"""
User provider implementation via Terraform/Tofu for Okta users using okta/okta

"""


class OktaTfUserBuilder(UserBuilderBase[OktaTfUserBuilderModel], TerraformRootMixin):
    """Okta user provider implementation via Terraform/Tofu.

    Owns its own terraform root (``<name>/user-generation/``) that creates
    Okta identities via the okta/okta provider's ``okta_user`` resource. Group
    membership is NOT attached here -- tfmodules/okta_opa_module attaches by
    username string in the group builder's root, and email_as_username keeps
    those usernames equal to the logins created here.
    """


    @classmethod
    def csis_name(cls) -> str:
        return OKTATF

    @property
    def model(self) -> OktaTfUserBuilderModel:
        return self._model  # type: ignore   # FIXME: This is dangerous

    def query_existing_users(self) -> list[User]:
        """Seam for lookup-only users (existing Okta identities to reference
        via data sources instead of creating). Not implemented yet."""
        return []

    def _users(self) -> list[User]:
        # Sorted: sort_and_write preserves insertion order, and deterministic
        # file order keeps generated diffs reviewable.
        return sorted(self.get_users_for_builder(), key=lambda u: u.get_name())

    def _okta_provider_ref(self) -> str | None:
        """Aliased provider reference for root-level resources (correction:
        the collector always aliases, so no default provider config exists)."""
        ref = TerraformCollector().provider_bindings(self.name).get(OKTA_PROVIDER)
        if ref is None:
            log.warning(
                f"User builder {self.name} has no configured '{OKTA_PROVIDER}' "
                f"provider; emitted resources will rely on a default provider "
                f"configuration that this workspace does not generate."
            )
        return ref

    def generate_items_before(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """The workspace scaffolding: terraform{} + provider blocks, variables
        (none expected -- okta credentials are environment-side), backend."""
        items: AssetSet = AssetSet()
        if phase != ExecutionLifecyclePhase.USER_GENERATION or not self._users():
            return items
        rpath = self.get_path_for_phase(phase, suffix=".tf")
        items = items.with_default_path(rpath)
        items.add(
            f"# Terraform configuration for Okta users generated by "
            f"{self.__class__.__name__} ({self.name})",
        )
        items.add("\n")
        col = TerraformCollector()
        self.model.register_hcl_requirements(self.name)
        # stage 34: values the emission must not carry in plaintext are
        # registered before the terraform block, so the external provider the
        # decrypting data source needs is declared with the others
        sensitive = partial(col.sensitive_ref, self.name)
        for user in self._users():
            OktaTFUser(user, sensitive=sensitive)
        items.add_list(col.generate_terraform_block(self.name))
        items.add("\n")
        items.add_list(col.generate_provider_blocks(self.name))
        sensitive_lines = col.generate_sensitive_blocks(self.name)
        if sensitive_lines:
            items.add("\n")
            items.add_list(sensitive_lines)
        variable_lines = col.generate_variable_blocks(self.name)
        if variable_lines:
            vpath = self.get_path_for_phase(
                phase, suffix=f"-{utils.safe_name(self.name)}-vars.tf")
            items.add_list(vpath, variable_lines)
        backend_lines = col.generate_backend_config(self.name)
        if backend_lines:
            items.add_list(self._backend_config_path(phase), backend_lines)
        return items

    def get_commands_to_run_before(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run before a specific execution lifecycle event."""
        return CFExecutables([], [])

    def generate_items_during(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """Per attached user: a managed user is an ``okta_user`` resource plus
        a lookup that depends on it; an unmanaged user is an eager lookup of
        the existing identity only (EXPLORE identity: one builder, two
        emission paths, chosen per item)."""
        items = AssetSet()
        if phase != ExecutionLifecyclePhase.USER_GENERATION or not self._users():
            return items
        rpath = self.get_path_for_phase(phase, USERS, suffix=".tf")
        dpath = self.get_path_for_phase(phase, USERS, suffix="-data.tf")
        provider_ref = self._okta_provider_ref()
        sensitive = partial(TerraformCollector().sensitive_ref, self.name)
        for user in self._users():
            if self.is_managed(user):
                otfu = OktaTFUser(user, provider=provider_ref, status=self.model.default_user_status,
                                  sensitive=sensitive)
                # OktaTFUser emits its own per-block comment line.
                items.add_list(rpath, otfu.generate_terraform())
                items.add(rpath, "\n")
            else:
                # No created resource to depend on: the lookup must resolve at
                # plan time against the existing Okta org.
                otfu = OktaTFUser(user, provider=provider_ref, lookup_depends_on=False,
                                  sensitive=sensitive)
            items.add_list(dpath, otfu.generate_terraform_data())
        return items

    # ------------------------------------------- EXPLORE identity hooks
    def validate_attributes(self, user: User, attributes: dict[str, Any]) -> list[str]:
        return validate_opa_attributes(f"user '{user.get_name()}'", attributes, OPA_USER_ATTRIBUTES)

    def query_attributes(self, user: User) -> dict[str, Any] | None:
        team, api_host = str(self.model.team), str(self.model.api_host)
        key, secret = credentials_from_env(team)
        return OpaGidResolver(api_host, team, key, secret).user_attributes(user.get_name())

    def get_commands_to_run_during(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run during a specific execution lifecycle event."""

        return CFExecutables([], [])

    def generate_items_after(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """Generate a list of items to create after a specific execution lifecycle event."""
        return AssetSet()

    def get_commands_to_run_after(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """fmt/init/validate always; plan only when okta credentials are
        exported (see the credentials runbook in PLAN.md). Skipped entirely
        when there are no users, so tofu never runs against an unwritten
        directory."""
        if phase != ExecutionLifecyclePhase.USER_GENERATION or not self._users():
            return CFExecutables([], [])
        arg_lists = [["fmt"], self._init_args(phase), ["validate"]]
        if self._dry_run():
            # a dry run initialises without the backend and touches no state;
            # the lookups are planned by a real run (or by hand after an init)
            log.info(f"User builder {self.name}: dry run, 'plan' not run at generation time")
        elif okta_credentials_present():
            arg_lists.append(["plan"])
        else:
            log.warning(
                f"User builder {self.name}: skipping 'plan' (no okta "
                f"credentials in the environment)."
            )
        wd = self.get_path_for_phase(phase, suffix=".tf").parent
        return CFExecutables(self.terraform_commands(phase, arg_lists, wd), [])
