# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""GCE instance plugin (GCP increment 3, PLAN.md gate 4).

One ``module`` call per instance against tfmodules/gce_instance. The boot
image is the instance's pinned build (the GCE image name), else the resolved
provider-specific image, else the per-instance variable with the series
*family* as fallback (GCE resolves "latest in family" natively). Launch
parameters (N26) arrive as ``metadata.startup-script`` -- the same generated
script the AWS root feeds through user-data -- with runtime values by
reference: gid from the identity workspace, Filestore ip/share from the
storage workspace; persistent disks attach through the module and appear
as ``/dev/disk/by-id/google-<storage>``.
"""
from __future__ import annotations

import logging
from typing import Any, TypeVar

from cs_image_system.base import utils
from cs_image_system.base.utils import HclRaw, hcl_expr, render_module_call
from cs_image_system.base.basic.asset import AssetSet
from cs_image_system.base.launch_params import ENROLLMENT_TOKEN_VARIABLE, compute_launch_params, user_data_template
from cs_image_system.base.lifecycle import ExecutionLifecyclePhase
from cs_image_system.base.models.instance import Instance
from cs_image_system.hashicorp_utils.collector import TerraformCollector, TerraformVariable
from cs_image_system.tf_ebs_instance_plugin.tf_instance_builder import TofuInstanceBuilder

from .tf_gcp_models import TOFU_GCE, TofuGceInstanceBuilderModel
from .tf_gcp_storage_builder import google_provider_config

log = logging.getLogger(__name__)

Q = TypeVar("Q", bound=TofuGceInstanceBuilderModel)


class TofuGceInstanceBuilder(TofuInstanceBuilder[Q]):
    @classmethod
    def csis_name(cls) -> str:
        return TOFU_GCE

    @staticmethod
    def _image_var(label: str) -> str:
        return f"{label}_image"

    @staticmethod
    def _ami_var(label: str) -> str:
        """The variable the inherited ``pre_finalize_phase`` writes into
        ``instances.auto.tfvars`` for a build this run baked: the GCE root
        declares ``<label>_image``, not the AWS root's ``<label>_ami_id``
        (stage 63 item 7: the tfvars line named a variable no GCE root
        declared, tofu warned, and the instance launched through
        ``image_family`` instead of the build)."""
        return TofuGceInstanceBuilder._image_var(label)

    def generate_items_before(self, phase: ExecutionLifecyclePhase) -> AssetSet:
        items = AssetSet()
        if phase != ExecutionLifecyclePhase.INSTANCE_GENERATION or not self._root_has_work():
            return items
        rpath = self.get_path_for_phase(phase, suffix=".tf")
        items = items.with_default_path(rpath)
        items.add(f"# Terraform configuration for GCE instances generated by "
                  f"{self.__class__.__name__} ({self.name})")
        col = TerraformCollector()
        ws = self.name
        self._declare_ephemeral_variable(col, ws)
        if self.model.required_plugins:
            for plugin in self.model.required_plugins:
                col.require_provider(ws, plugin.name, source=getattr(plugin, "source", None),
                                     version=getattr(plugin, "version", None))
        else:
            col.require_provider(ws, "google", source="hashicorp/google")
        cfg = google_provider_config(self._runtime_builder())
        if cfg:
            col.configure_provider(ws, "google", cfg)
        for instance in self._instances:
            label = utils.super_safe_name(instance.get_name())
            col.declare_variable(ws, TerraformVariable(name=self._image_var(label), type="string", default=""))
        col.declare_variable(ws, TerraformVariable(
            name=ENROLLMENT_TOKEN_VARIABLE, type="string", default="", sensitive=True,
            description="Identity enrollment token handed to instances at launch (TF_VAR_...); empty = no enrollment"))
        col.bind_workspace(ws, self.model.state_configuration, self.runtime_state_configuration())   # stage 46: own, runtime's, default
        ctx = self._get_context()
        for sb_name, sb in ctx.storage_builders.items():
            if getattr(sb.model, "_storages", None):
                col.reference_remote_state(ws, producer_workspace=sb_name)
        identity_ws: set[str] = set()
        for instance in self._instances:
            image = ctx.images_map.get(str(instance.image)) if instance.image else None
            iws = self._identity_workspace_for(getattr(image, "group", None))
            if iws:
                identity_ws.add(iws)
        for iws in sorted(identity_ws):
            col.reference_remote_state(ws, producer_workspace=iws)
        items.add_list(col.generate_terraform_block(ws))
        items.add_list(col.generate_provider_blocks(ws))
        variable_lines = col.generate_variable_blocks(ws)
        if variable_lines:
            items.add_list(variable_lines)
        remote_lines = col.generate_remote_state_datasources(ws)
        if remote_lines:
            items.add_list(remote_lines)
        backend_lines = col.generate_backend_config(ws)
        if backend_lines:
            items.add_list(self._backend_config_path(phase), backend_lines)
        return items

    def generate_items_during(self, phase: ExecutionLifecyclePhase) -> AssetSet:
        items = AssetSet()
        if phase != ExecutionLifecyclePhase.INSTANCE_GENERATION or not self._root_has_work():
            return items                                    # ledger 70: outside --only-runtime, nothing
        ctx = self._get_context()
        rtb = self._runtime_builder()
        src = utils.module_source("gce_instance", self.get_path_for_phase(phase, suffix=".tf").parent)
        bindings = TerraformCollector().provider_bindings(self.name)
        for instance in self._instances:
            label = utils.super_safe_name(instance.get_name())
            rpath = self.get_path_for_phase(phase, f"instance-{label}", suffix=".tf")
            params = compute_launch_params(ctx, instance)
            items.add(rpath, f"# Terraform module call for GCE instance {instance.get_name()} "
                             f"generated by {self.__class__.__name__} ({self.name})")
            if params.get("group"):
                items.add(rpath, f"# owning group: {params['group']} (via image {instance.image}); "
                                 f"launch parameters recorded in meta-state/launch-params.yaml (N26)")
            items.add_list(rpath, render_module_call(
                f"instance_{label}", src, self._with_ephemeral_count(instance, self._module_args(ctx, rtb, instance, params)),
                providers=bindings))
            tpath = rpath.parent / self._user_data_template_name(label)
            items.add(tpath, user_data_template(params))
        return items

    def _module_args(self, ctx, rtb, instance: Instance, params: dict[str, Any] | None = None) -> dict[str, Any]:
        from cs_image_system.base.lineage import pinned_instance_build
        from cs_image_system.gcloud_runtime.gcp_packer_source import gce_name
        label = utils.super_safe_name(instance.get_name())
        args: dict[str, Any] = {"name": gce_name(instance.get_name())}
        pinned = pinned_instance_build(ctx, instance) if hasattr(ctx, "meta_state") else None
        psi = (ctx.get_provider_specific_image(instance.image, rtb.get_name()) if rtb and instance.image else None)
        if pinned:
            args["image"] = pinned
        elif psi is not None and psi.is_resolved():
            args["image"] = psi.identifier
        elif psi is not None:
            # built later: the per-instance variable (filled by finalization
            # from the packer manifest); the series family is the fallback
            args["image"] = f"var.{self._image_var(label)}"
            args["image_family"] = gce_name(str(instance.image))
        else:
            log.warning(f"No provider-specific image for image {instance.image!r} of instance "
                        f"{instance.get_name()}; the module call will not resolve an image")
        if rtb:
            args["machine_type"] = rtb.get_default_machine_type()
            zone = getattr(rtb.model, "zone", None)
            if zone:
                args["zone"] = zone
            networking = getattr(rtb.model, "networking", None)
            subnet = getattr(networking, "default_subnet_id", None) if networking else None
            if subnet:
                args["subnetwork"] = subnet
            tags = list(getattr(networking, "network_tags", None) or []) if networking else []
            if tags:
                args["network_tags"] = tags
            if rtb.session_mechanism() == "iap":
                # no public IP: the IAP tunnel is the way in (operator prerequisite:
                # firewall rule from 35.235.240.0/20 to tcp:22)
                args["public_ip"] = False
        labels = {k: str(v) for k, v in (instance.get_tags() or {}).items()}
        if labels:
            from cs_image_system.gcloud_runtime.gcp_packer_source import gce_label
            args["labels"] = {gce_label(k): gce_label(v) for k, v in labels.items()}
        if params is not None:
            args.update(self._launch_args(ctx, label, params))
        return args

    def _launch_args(self, ctx, label: str, params: dict[str, Any]) -> dict[str, Any]:
        out: dict[str, Any] = {}
        group = params.get("group")
        identity_ws = self._identity_workspace_for(group)
        template_vars: dict[str, Any] = {}
        if group and identity_ws:
            template_vars["group_gid"] = HclRaw(
                f'data.terraform_remote_state.{utils.super_safe_name(identity_ws)}.outputs.group_gids["{group}"]')
        disks: dict[str, Any] = {}
        filestore: dict[str, Any] = {}
        for m in params.get("mounts", []):
            sb = m.get("builder") or self._storage_builder_name(m["storage"])
            if not sb:
                continue
            ref = (f"data.terraform_remote_state.{utils.super_safe_name(sb)}"
                   f".outputs.storage_{utils.super_safe_name(m['storage'])}")
            if m["type"] == "pd":
                # finding 50 (found live on gce-test): the disk was attached as
                # device_name "gce_data" while the launch params mount
                # /dev/disk/by-id/google-gce-data (the by-id name is
                # "google-<device_name>"), so the startup script died at the
                # missing device and nothing was ever mounted. One
                # sanitization for both: the by-id path's suffix IS the
                # device name.
                from cs_image_system.gcloud_runtime.gcp_packer_source import gce_name
                disks[m["storage"]] = {"disk_self_link": HclRaw(f"{ref}.self_link"),
                                       "device_name": gce_name(m["storage"])}
            elif m["type"] == "filestore":
                filestore[m["storage"]] = {"ip_address": HclRaw(f"{ref}.ip_address"),
                                           "share_name": HclRaw(f"{ref}.share_name")}
        template_vars["efs"] = {}
        template_vars["filestore"] = filestore
        enrollment = params.get("enrollment") or {}
        template_vars[ENROLLMENT_TOKEN_VARIABLE] = (HclRaw(f"var.{ENROLLMENT_TOKEN_VARIABLE}") if enrollment else "")
        tpl = self._user_data_template_name(label)
        out["startup_script"] = HclRaw(f'templatefile("${{path.module}}/{tpl}", {hcl_expr(template_vars, 2)})')
        if disks:
            out["attached_disks"] = disks
        return out

    def _attachment_address(self, instance_name: str, storage: str) -> str | None:
        return None   # attached_disk is an in-place attribute of google_compute_instance

    def _module_address(self, instance_name: str) -> str:
        return f"module.instance_{utils.super_safe_name(instance_name)}"

    def _replacements(self) -> list[str]:
        ctx = self._get_context()
        from cs_image_system.base.lineage import pending_instance_replacements
        names = pending_instance_replacements(ctx, self._instances)   # upgrades + follow (stage 9)
        return [f"{self._module_address(n)}.google_compute_instance.this" for n in sorted(names)]
