# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

"""GCP storage plugins (GCP increment 3, PLAN.md gates 2-3, 6).

Three capability types on a GCE runtime, each reusing the AWS tofu storage
machinery (one terraform root per builder, module call per storage, gids by
remote-state reference, the storage state machine, the apply gate):

* ``pd`` -- persistent disk, single-attach, POSIX (EBS equivalent);
* ``filestore`` -- NFS, many-attach, POSIX (EFS equivalent; no access
  points, so the per-group subtree is created and chgrp'ed at first mount
  by the launch parameters);
* ``gcs`` -- bucket, many-attach, non-POSIX (S3 equivalent).

The google provider is configured from the runtime builder (project, region,
zone, optional service-account key file). Storage state queries use the
compute client for disks; Filestore/GCS need client libraries that are not
dependencies yet and report as *unavailable*.
"""
from __future__ import annotations

import logging
from typing import Any, TypeVar, cast

from cs_image_system.base import utils
from cs_image_system.base.constants import OOPS_DEFAULTS
from cs_image_system.base.basic.asset import AssetSet
from cs_image_system.base.basic.builder_base_storage import CARDINALITY_MANY, CARDINALITY_SINGLE
from cs_image_system.base.lifecycle import ExecutionLifecyclePhase
from cs_image_system.base.models.executable import ExecutableModel
from cs_image_system.base.models.storage import STORAGE_STATE_ACTIVE, STORAGE_STATE_ARCHIVED, STORAGE_STATE_DESTROYED, Storage
from cs_image_system.hashicorp_utils.collector import TerraformCollector
from cs_image_system.tf_ebs_instance_plugin.tf_storage_builder import TofuStorageBuilder, _groups, _public_read

from .tf_gcp_models import (
    TF_GCP, TF_GCP_FILESTORE, TF_GCP_GCS, TF_GCP_PD,
    TofuFilestoreStorageBuilderModel, TofuGcpStorageBuilderModel, TofuGcsStorageBuilderModel,
    TofuPdStorageBuilderModel,
)

log = logging.getLogger(__name__)

Q = TypeVar("Q", bound=TofuGcpStorageBuilderModel)


def google_provider_config(rtb: Any) -> dict[str, Any]:
    """``provider "google"`` arguments from a GCP runtime builder model."""
    model = getattr(rtb, "model", None)
    cfg: dict[str, Any] = {}
    if model is None:
        return cfg
    for src, dst in (("project_id", "project"), ("region", "region"), ("zone", "zone")):
        v = getattr(model, src, None)
        if v:
            cfg[dst] = str(v)
    # Credentials come from the environment only (GOOGLE_APPLICATION_CREDENTIALS
    # or ADC), never from generated IaC -- the same rule as the AWS roots' profile.
    return cfg


class TofuGcpStorageBuilder(TofuStorageBuilder[Q]):
    """Base of the GCP storage plugins: swaps the aws provider block for a
    google one; everything else is inherited."""

    @classmethod
    def csis_name(cls) -> str:
        return TF_GCP

    def _runtime(self):
        return self._get_context().runtime_builders.get(self.model.get_runtime_provider(), None)

    def _zone(self) -> str | None:
        rtb = self._runtime()
        return getattr(rtb.model, "zone", None) if rtb else None

    def generate_items_before(self, phase: ExecutionLifecyclePhase) -> AssetSet:
        items = AssetSet()
        # declared storages OR undeclared ones still to destroy (stage 10.11)
        if phase != ExecutionLifecyclePhase.STORAGE_GENERATION or not self._has_work():
            return items
        rpath = self.get_path_for_phase(phase, suffix=".tf")
        items = items.with_default_path(rpath)
        items.add(f"# Terraform configuration for GCP storages generated by "
                  f"{self.__class__.__name__} ({self.name})")
        col = TerraformCollector()
        ws = self.name
        if self.model.required_plugins:
            for plugin in self.model.required_plugins:
                col.require_provider(ws, plugin.name, source=getattr(plugin, "source", None),
                                     version=getattr(plugin, "version", None))
        else:
            col.require_provider(ws, "google", source="hashicorp/google")
        cfg = google_provider_config(self._runtime())
        if cfg:
            col.configure_provider(ws, "google", cfg)
        col.bind_workspace(ws, self.model.state_configuration, self.runtime_state_configuration())   # stage 46: own, runtime's, default
        for identity_ws in sorted(self.identity_workspaces()):
            col.reference_remote_state(ws, producer_workspace=identity_ws)
        items.add_list(col.generate_terraform_block(ws))
        items.add_list(col.generate_provider_blocks(ws))
        remote_lines = col.generate_remote_state_datasources(ws)
        if remote_lines:
            items.add_list(remote_lines)
        backend_lines = col.generate_backend_config(ws)
        if backend_lines:
            items.add_list(self._backend_config_path(phase), backend_lines)
        return items

    @staticmethod
    def _gce_resource_name(name: str) -> str:
        """GCE resource names must match ``[a-z]([-a-z0-9]*[a-z0-9])?`` --
        found live: a disk named ``gce_data`` fails the apply. Same rule the
        packer sources apply via ``gce_name``."""
        from cs_image_system.gcloud_runtime.gcp_packer_source import gce_name
        return gce_name(name)

    def _labels(self, storage: Storage) -> dict[str, str]:
        from cs_image_system.gcloud_runtime.gcp_packer_source import gce_label
        # stage 26: the builder's declared default labels under the item's own
        merged = getattr(self.model, "variables", None)
        base = merged.merged_tags(storage.tags) if merged is not None else dict(storage.tags or {})
        labels = {gce_label(k): gce_label(str(v)) for k, v in base.items()}
        labels["csis_storage"] = gce_label(storage.get_name())
        for g in sorted(_groups(storage)):
            labels[f"csis_group_{gce_label(g)}"] = "true"
        return labels

    # state query: subclasses that can ask do; the rest are "unavailable"
    def _lookup(self, storage: Storage) -> dict[str, Any] | None:
        raise NotImplementedError(f"{self.__class__.__name__} cannot query storage state yet")


R = TypeVar("R", bound=TofuPdStorageBuilderModel)
class TofuPdStorageBuilder(TofuGcpStorageBuilder[R]):
    @classmethod
    def csis_name(cls) -> str:
        return TF_GCP_PD

    @classmethod
    def capability_type(cls) -> str:
        return "pd"

    def is_zonal(self) -> bool:
        return True     # stage 52: a persistent disk lives in one zone; changing it replaces the volume

    def attachment_cardinality(self) -> str:
        return CARDINALITY_SINGLE

    def base_image_prerequisites(self, os_family: str | None = None) -> list[str]:
        return [f"# storage type 'pd' declared: no prerequisites to bake ({self.get_name()})"]

    def module_dirname(self) -> str:
        return "gcp_storage_pd"

    def module_args(self, storage: Storage) -> dict[str, Any]:
        args: dict[str, Any] = {
            "name": self._gce_resource_name(storage.get_name()),
            "size": getattr(self.model, "size", 100),
            "disk_type": getattr(self.model, "disk_type", "pd-balanced"),
            "labels": self._labels(storage),
        }
        zone = self._zone()
        if zone:
            args["zone"] = zone
        # restore (stage 11.6): recorded archived, declared active -> the disk
        # is created FROM the archive snapshot; the module ignores later drift
        if self._get_context().meta_state.storage_state(storage.get_name()) == STORAGE_STATE_ARCHIVED:
            args["snapshot"] = self.archive_name(storage)
        return args

    # ------------------------------------------------ archived (stage 11.6)
    def supports_archive(self) -> bool:
        return True

    def archive_name(self, storage: Storage) -> str:
        return f"csis-{self._gce_resource_name(storage.get_name())}-archive"

    def _project(self) -> str | None:
        from cs_image_system.gcloud_runtime.gcp_utils import resolve_project
        rtb = self._runtime()
        to_cfg: Any = getattr(getattr(rtb, "model", None), "self_to_gcp_client_config", None)
        return resolve_project(cast(dict[str, Any], to_cfg())) if callable(to_cfg) else None

    def _script(self, storage: Storage, name: str, body: str) -> ExecutableModel:
        wd = self.get_path_for_phase(ExecutionLifecyclePhase.STORAGE_GENERATION, suffix=".tf").parent
        target = self._get_context().generation_path / wd / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("#!/usr/bin/env bash\nset -uo pipefail\n" + body)
        e = ExecutableModel(name="bash", type_="executable", binary="bash")
        e.args = [name]
        e.working_directory = wd
        return e

    def transition_actions(self, storage: Storage, from_state: str | None,
                           to_state: str) -> list[ExecutableModel]:
        disk, snap = self._gce_resource_name(storage.get_name()), self.archive_name(storage)
        project, zone = self._project(), self._zone()
        if to_state == STORAGE_STATE_ARCHIVED and from_state == STORAGE_STATE_ACTIVE:
            # snapshot the disk BEFORE terraform destroys it; a snapshot left by
            # an earlier attempt is reused (the archive is the name)
            return [self._script(storage, f"archive-{disk}.sh",
                f'if gcloud compute snapshots describe "{snap}" --project "{project}" >/dev/null 2>&1; then\n'
                f'  echo "archive {snap} already exists"; exit 0\nfi\n'
                f'gcloud compute disks snapshot "{disk}" --snapshot-names "{snap}" --zone "{zone}" '
                f'--project "{project}" --quiet\n')]
        if to_state == STORAGE_STATE_DESTROYED and from_state == STORAGE_STATE_ARCHIVED:
            # the disk is already gone; the archive goes with the demise
            return [self._script(storage, f"unarchive-{disk}.sh",
                f'gcloud compute snapshots delete "{snap}" --project "{project}" --quiet 2>&1 '
                f'| grep -v "was not found" || true\n')]
        return []

    def post_transition_actions(self, storage: Storage, from_state: str | None,
                                to_state: str) -> list[ExecutableModel]:
        disk, snap = self._gce_resource_name(storage.get_name()), self.archive_name(storage)
        project = self._project()
        if from_state == STORAGE_STATE_ARCHIVED and to_state == STORAGE_STATE_ACTIVE:
            # restored: the data is on the disk again; the archive is deleted
            return [self._script(storage, f"restore-{disk}.sh",
                f'gcloud compute snapshots delete "{snap}" --project "{project}" --quiet\n')]
        return []

    def _lookup(self, storage: Storage) -> dict[str, Any] | None:
        from google.cloud import compute_v1  # noqa: PLC0415
        from cs_image_system.gcloud_runtime.gcp_utils import _make_credentials, resolve_project
        rtb = self._runtime()
        to_cfg: Any = getattr(getattr(rtb, "model", None), "self_to_gcp_client_config", None)
        cfg: dict[str, Any] = cast(dict[str, Any], to_cfg()) if callable(to_cfg) else {}
        project, zone = resolve_project(cfg), self._zone()
        if not project or not zone:
            raise RuntimeError("no project/zone to query")
        creds = _make_credentials(cfg)
        client = compute_v1.DisksClient(credentials=creds) if creds else compute_v1.DisksClient()
        if self._get_context().meta_state.storage_state(storage.get_name()) == STORAGE_STATE_ARCHIVED:
            # archived (stage 11.6): the disk is expected absent; the archive
            # snapshot is what must exist
            try:
                snap = compute_v1.SnapshotsClient(credentials=creds).get(project=project, snapshot=self.archive_name(storage)) \
                    if creds else compute_v1.SnapshotsClient().get(project=project, snapshot=self.archive_name(storage))
            except Exception as e:  # noqa: BLE001
                if "404" in str(e) or "not found" in str(e).lower():
                    return None
                raise
            return {"id": snap.name, "state": "archived", "snapshot": snap.name, "tags": dict(getattr(snap, "labels", {}) or {})}
        try:
            d = client.get(project=project, zone=zone, disk=self._gce_resource_name(storage.get_name()))
        except Exception as e:  # NotFound -> absent; anything else -> unavailable
            if e.__class__.__name__ == "NotFound":
                return None
            raise
        return {"id": d.name, "state": str(getattr(d, "status", "")), "size": int(getattr(d, "size_gb", 0)),
                "tags": dict(getattr(d, "labels", {}) or {})}


S = TypeVar("S", bound=TofuFilestoreStorageBuilderModel)
class TofuFilestoreStorageBuilder(TofuGcpStorageBuilder[S]):
    @classmethod
    def csis_name(cls) -> str:
        return TF_GCP_FILESTORE

    @classmethod
    def capability_type(cls) -> str:
        return "filestore"

    def attachment_cardinality(self) -> str:
        return CARDINALITY_MANY

    def base_image_prerequisites(self, os_family: str | None = None) -> list[str]:
        fam = (os_family or "").lower()
        pkg = "sudo apt-get -o DPkg::Lock::Timeout=600 install -y nfs-common" if fam in ("debian", "ubuntu") else "sudo yum install -y nfs-utils"
        return [f"# storage type 'filestore' prerequisites ({self.get_name()}): NFS mount tooling", pkg]

    def verify_commands(self, os_family: str | None = None) -> list[str]:
        return ["# verify: NFS mount tooling present",
                "command -v mount.nfs >/dev/null 2>&1 || command -v mount.nfs4 >/dev/null 2>&1"]

    def module_dirname(self) -> str:
        return "gcp_storage_filestore"

    def module_args(self, storage: Storage) -> dict[str, Any]:
        rtb = self._runtime()
        networking = getattr(rtb.model, "networking", None) if rtb else None
        args: dict[str, Any] = {
            "name": self._gce_resource_name(storage.get_name()),
            "tier": getattr(self.model, "tier", "BASIC_HDD"),
            "capacity_gb": getattr(self.model, "capacity_gb", 1024),
            "labels": self._labels(storage),
        }
        zone = self._zone()
        if zone:
            args["zone"] = zone
        network = getattr(networking, "network", None) if networking else None
        if network and network not in OOPS_DEFAULTS:
            args["network"] = network
        if _groups(storage):
            # No access points on Filestore: the per-group subtree is created
            # and chgrp'ed (gid by reference) at first mount by the launch
            # parameters; the module only records the intent as labels.
            args["group_subtrees"] = sorted(_groups(storage))
        if _public_read(storage):
            args["public_read"] = True
        return args


G = TypeVar("G", bound=TofuGcsStorageBuilderModel)
class TofuGcsStorageBuilder(TofuGcpStorageBuilder[G]):
    @classmethod
    def csis_name(cls) -> str:
        return TF_GCP_GCS

    @classmethod
    def capability_type(cls) -> str:
        return "gcs"

    def attachment_cardinality(self) -> str:
        return CARDINALITY_MANY

    def is_posix(self) -> bool:
        return False

    def base_image_prerequisites(self, os_family: str | None = None) -> list[str]:
        return [f"# storage type 'gcs' prerequisites ({self.get_name()}): gcloud CLI for object access",
                "command -v gcloud >/dev/null 2>&1 || (curl -fsSL https://sdk.cloud.google.com | sudo bash -s -- --disable-prompts --install-dir=/opt && sudo ln -sf /opt/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud)"]

    def verify_commands(self, os_family: str | None = None) -> list[str]:
        return ["# verify: gcloud CLI present", "command -v gcloud >/dev/null 2>&1"]

    def module_dirname(self) -> str:
        return "gcp_storage_gcs"

    def module_args(self, storage: Storage) -> dict[str, Any]:
        rtb = self._runtime()
        args: dict[str, Any] = {
            "bucket_name": getattr(storage, "bucket_name", None) or getattr(self.model, "bucket_name", None) or storage.get_name(),
            "labels": self._labels(storage),
        }
        location = getattr(self.model, "location", None) or (getattr(rtb.model, "region", None) if rtb else None)
        if location:
            args["location"] = str(location)
        if _groups(storage):
            args["group_prefixes"] = sorted(_groups(storage))
        if _public_read(storage):
            args["public_read"] = True
        return args

    def transition_actions(self, storage: Storage, from_state: str | None,
                           to_state: str) -> list[ExecutableModel]:
        """``destroyed`` wipes the bucket before terraform removes it (N19).

        The wipe is a generated script, not a bare ``gcloud storage rm``:
        gcloud exits 1 when ``gs://bucket/**`` matches nothing, and an
        EMPTY bucket is the normal case at the end of a change cycle
        (found live, stage 8: the teardown died on the wipe of an empty
        bucket). "Matched no objects" is success; every other failure
        still stops the run before terraform's destroy."""
        if to_state != STORAGE_STATE_DESTROYED:
            return []
        bucket = getattr(storage, "bucket_name", None) or getattr(self.model, "bucket_name", None) or storage.get_name()
        wd = self.get_path_for_phase(ExecutionLifecyclePhase.STORAGE_GENERATION, suffix=".tf").parent
        script = self.wipe_script_name(storage)
        ctx = self._get_context()
        target = ctx.generation_path / wd / script
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            "#!/usr/bin/env bash\n"
            f"# Wipe gs://{bucket} before terraform destroys it (storage {storage.get_name()} -> destroyed).\n"
            "set -uo pipefail\n"
            f'out=$(gcloud storage rm --recursive "gs://{bucket}/**" 2>&1); rc=$?\n'
            'if [ "$rc" -ne 0 ] && grep -q "matched no objects" <<<"$out"; then\n'
            f'  echo "gs://{bucket} is already empty"; exit 0\n'
            "fi\n"
            'printf "%s\\n" "$out"; exit "$rc"\n')
        e = ExecutableModel(name="bash", type_="executable", binary="bash")
        e.args = [script]
        e.working_directory = wd
        return [e]

    @staticmethod
    def wipe_script_name(storage: Storage) -> str:
        return f"wipe-{utils.super_safe_name(storage.get_name())}.sh"

    def _lookup(self, storage: Storage) -> dict[str, Any] | None:
        """State-query parity for GCS (GCP-READINESS §7) without a new client
        library: ``gcloud storage buckets describe`` -- the same CLI the
        wipe relies on. Not found -> absent; any other failure -> the query
        reports the bucket unavailable (never a silent no-claim)."""
        import json  # noqa: PLC0415
        import subprocess  # noqa: PLC0415
        bucket = getattr(storage, "bucket_name", None) or getattr(self.model, "bucket_name", None) or storage.get_name()
        res = subprocess.run(["gcloud", "storage", "buckets", "describe", f"gs://{bucket}", "--format=json"],
                             capture_output=True, text=True, check=False)
        if res.returncode != 0:
            err = (res.stderr or "").strip()
            if "not found" in err.lower() or "404" in err or "does not exist" in err.lower():
                return None
            raise RuntimeError(f"gcloud storage buckets describe gs://{bucket}: {err[-300:]}")
        info = json.loads(res.stdout or "{}")
        return {"id": info.get("name") or bucket, "state": "active",
                "location": info.get("location"), "storage_class": info.get("storageClass"),
                "tags": dict(info.get("labels") or {})}
