# Terraform module call for instance test generated by TofuInstanceBuilder (open-tofu)
# owning group: coops (via image imgfile-basic-cloudflow); launch parameters recorded in meta-state/launch-params.yaml (N26)
module "instance_test" {
  source = "../../../../../tfmodules/aws_instance"
  providers = { aws = aws.open_tofu }
  name = "test"
  ami_id = var.test_ami_id
  ami_name_pattern = "imgfile-basic-cloudflow-some-other-builder*"
  instance_type = "t2.micro"
  subnet_id = "subnet-09f79018af845358a"
  iam_instance_profile = "AmazonSSMRoleForInstancesQuickSetup"
  tags = { "stype" = "test" }
  user_data = templatefile("${path.module}/user-data-test.sh.tftpl", {
    "efs" = {}
    "group_gid" = data.terraform_remote_state.oktagroups.outputs.group_gids["coops"]
    "sft_enrollment_token" = var.sft_enrollment_token
  })
}