# Terraform module call for instance test2 generated by TofuInstanceBuilder (open-tofu)
# owning group: coops (via image imgfile-basic-dask); launch parameters recorded in meta-state/launch-params.yaml (N26)
module "instance_test2" {
  source = "../../../../../tfmodules/aws_instance"
  providers = { aws = aws.open_tofu }
  name = "test2"
  ami_id = var.test2_ami_id
  ami_name_pattern = "imgfile-basic-dask-pckr-ebs-ans*"
  instance_type = "t2.micro"
  subnet_id = "subnet-09f79018af845358a"
  iam_instance_profile = "AmazonSSMRoleForInstancesQuickSetup"
  tags = { "hype" = "test" }
  user_data = templatefile("${path.module}/user-data-test2.sh.tftpl", {
    "efs" = {}
    "group_gid" = data.terraform_remote_state.oktagroups.outputs.group_gids["coops"]
    "sft_enrollment_token" = var.sft_enrollment_token
  })
  ebs_volumes = {
    "mnt_data" = {
      "device_name" = "/dev/xvdf"
      "volume_id" = data.terraform_remote_state.aws_ebs.outputs.storage_mnt_data.volume_id
    }
  }
}