# Terraform configuration for instances generated by TofuInstanceBuilder (open-tofu)
terraform {
    required_providers {
        aws = {
            source = "hashicorp/aws"
            version = ">= 4.0.0"
        }
    }
    
    backend "s3" {
    }
}
provider "aws" {
    region = "us-east-2"
    profile = "noaa"
    alias = "open_tofu"
}
variable "test_ami_id" {
    type = string
    default = ""
}
variable "test2_ami_id" {
    type = string
    default = ""
}
variable "sft_enrollment_token" {
    type = string
    default = ""
    description = "Identity enrollment token handed to instances at launch (TF_VAR_...); empty = no enrollment"
    sensitive = true
}
data "terraform_remote_state" "aws_efs" {
    backend = "s3"
    
    config = {
        bucket = "noaa-ioos-cloud-sandbox-tfstate"
        key = "statefiles/csia-image-system-test/aws_efs.tfstate"
        region = "us-east-2"
        profile = "noaa"
    }
}
data "terraform_remote_state" "aws_ebs" {
    backend = "s3"
    
    config = {
        bucket = "noaa-ioos-cloud-sandbox-tfstate"
        key = "statefiles/csia-image-system-test/aws_ebs.tfstate"
        region = "us-east-2"
        profile = "noaa"
    }
}
data "terraform_remote_state" "aws_s3" {
    backend = "s3"
    
    config = {
        bucket = "noaa-ioos-cloud-sandbox-tfstate"
        key = "statefiles/csia-image-system-test/aws_s3.tfstate"
        region = "us-east-2"
        profile = "noaa"
    }
}
data "terraform_remote_state" "oktagroups" {
    backend = "s3"
    
    config = {
        bucket = "noaa-ioos-cloud-sandbox-tfstate"
        key = "statefiles/csia-image-system-test/oktagroups.tfstate"
        region = "us-east-2"
        profile = "noaa"
    }
}