# SPDX-FileCopyrightText: 2026 Mykel Alvis <mykelalvis@infrastructurebuilder.org>
#
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path

from cs_image_system.base.basic.asset import Asset, AssetSet
from cs_image_system.base.basic.builder_base_group import GroupBuilderBase
from cs_image_system.base.basic.builder_base_user import UserBuilderBase
from cs_image_system.base.lifecycle import ExecutionLifecyclePhase
from cs_image_system.base.models.executable import ExecutableModel
from cs_image_system.base.models.executable_adds import CFExecutables
from cs_image_system.base.models.user import User

from .dummy_models import DUMMY, DummyGroupBuilderModel, DummyUserBuilderModel


"""
Group provider implementation via Terraform/Tofu for Dummy groups using Dummy/Dummypam

"""



# TODO Specific type configs for DefaultGroupProvider if needed
class DummyGroupBuilder(GroupBuilderBase[DummyGroupBuilderModel]):
    """Dummy group provider implementation via Terraform/Tofu."""
    @classmethod
    def csis_name(cls) -> str:
        return DUMMY


    @property
    def model(self) -> DummyGroupBuilderModel:
        return self._model # type: ignore   # FIXME: This is dangerous

    def generate_items_before(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet: # list[tuple[Path, str]]:
        """Generate a list of items to create before a specific execution lifecycle
        event."""
        # items: list[tuple[Path, str]] = []
        items: AssetSet = AssetSet()
        if phase == ExecutionLifecyclePhase.GROUP_GENERATION:
          ...
        return items

    def get_commands_to_run_before(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run before a specific execution lifecycle event."""
        return CFExecutables([], [])

    def generate_items_during(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """Generate the items to create during a specific execution lifecycle
        event: none, as an ``AssetSet`` (the contract's type; the generators
        call ``sort_and_write`` on it, and a bare list broke the identity
        lifecycle for any declared ``type: dummy`` builder -- stage 63 item 1)."""
        return AssetSet()

    def get_commands_to_run_during(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run during a specific execution lifecycle event."""
        return CFExecutables([], [])

    def generate_items_after(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet: #  list[tuple[Path, str]]:
        """Generate a list of items to create after a specific execution lifecycle event."""
        return AssetSet()

    def get_commands_to_run_after(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run after a specific execution lifecycle event."""
        # return ([],[]) # Shortcut!
        commands: list[ExecutableModel] = []
        if phase == ExecutionLifecyclePhase.GROUP_GENERATION:
          ...
        return CFExecutables(commands, [])


# TODO Specific type configs for DefaultGroupProvider if needed
class DummyUserBuilder(UserBuilderBase[DummyUserBuilderModel]):
    # class DummyUserBuilder(UserBuilderBase[DummyUserBuilderModel, User]):
    """Dummy user provider implementation via Terraform/Tofu."""


    @classmethod
    def csis_name(cls) -> str:
        return DUMMY


    def query_existing_users(self) -> list[User]:
        return []

    def get_subpath(self) -> Path:
        return Path("Dummy-tf")  # TODO

    def generate_items_before(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet: # list[tuple[Path, str]]:
        """Generate a list of items to create before a specific execution lifecycle
        event."""
        files: AssetSet = AssetSet()
        if phase == ExecutionLifecyclePhase.USER_GENERATION:
            rpath = self.get_subpath() / f"{DUMMY}_users.tf"
            files.append(
                Asset((
                    rpath,
                    f"# Terraform configuration for Dummy users generated by "
                    f"{self.__class__.__name__}\n",
                ))
            )
        return files

    def get_commands_to_run_before(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run before a specific execution lifecycle event."""
        commands: list[ExecutableModel] = []
        return CFExecutables(commands, [])

    def generate_items_during(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet:
        """Generate the items to create during a specific execution lifecycle
        event: none, as an ``AssetSet`` (stage 63 item 1)."""
        return AssetSet()

    def get_commands_to_run_during(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run during a specific execution lifecycle event."""

        return CFExecutables([], [])

    def generate_items_after(
        self, phase: ExecutionLifecyclePhase
    ) -> AssetSet: # list[tuple[Path, str]]:
        """Generate a list of items to create after a specific execution lifecycle event."""
        return AssetSet()

    def get_commands_to_run_after(
        self, phase: ExecutionLifecyclePhase
    ) -> CFExecutables:
        """Get a list of commands to run after a specific execution lifecycle event."""
        commands: list[ExecutableModel] = []
        after: list[ExecutableModel] = []
        return CFExecutables(commands, after)
