# Terraform module call for storage mnt_data generated by TofuEbsStorageBuilder (aws-ebs)
# allowed groups: coops (gids by remote-state reference); public_read=false; requested state: active
module "storage_mnt_data" {
  source = "../../../../../tfmodules/aws_storage_ebs"
  providers = { aws = aws.aws_ebs }
  name = "mnt_data"
  size = 100
  subnet_id = "subnet-09f79018af845358a"
}
output "storage_mnt_data" {
    value = module.storage_mnt_data
    description = "Outputs of storage mnt_data for remote-state consumers"
}